/* 
 * File:   ChatEvent.cpp
 * Author: dipal
 * 
 * Created on August 16, 2015, 6:00 PM
 */

#include "ChatEvent.h"

#include "Logger.h"

#define module "ChatEvent"

namespace imsdk {
    
std::vector<std::string> ChatEvent::eventNames;

ChatEvent::ChatEvent() {
    eventType = NO_EVENT;
}

ChatEvent::ChatEvent(EventType eventType, std::shared_ptr< PacketDTO> packet, ChatError errorCode) :
        packet(packet), eventType(eventType), errorCode(errorCode)
{
    Log(module, "Creating event "<<ChatEvent::getEventName(eventType));
}

ChatEvent::EventType ChatEvent::getEventType()
{
    return eventType;
}

std::shared_ptr< PacketDTO> ChatEvent::getPacket()
{
    return packet;
}

ChatError ChatEvent::getErrorCode()
{
    return errorCode;
}
    
ChatEvent::~ChatEvent() {
}

std::string ChatEvent::getEventName(EventType eventType)
{
    std::string eventName = ChatEvent::eventNames[eventType];
    if (eventName=="") {
        std::stringstream sout;
        sout<<eventType;
        eventName = sout.str();
    }
    
    return eventName;
}

void ChatEvent::initEventNames()
{
    ChatEvent::eventNames = std::vector<std::string>(500);
    ChatEvent::eventNames[EVENT_HANDLER_ATTACHED] = "EVENT_HANDLER_ATTACHED";
    ChatEvent::eventNames[EVENT_HANDLER_DETACHED] = "EVENT_HANDLER_DETACHED";
    ChatEvent::eventNames[FRIEND_REGISTER_SUCCESS] = "FRIEND_REGISTER_SUCCESS";
    ChatEvent::eventNames[FRIEND_REGISTER_FAILURE] = "FRIEND_REGISTER_FAILURE";
    ChatEvent::eventNames[FRIEND_REGISTRATION_EXPIRED] = "FRIEND_REGISTRATION_EXPIRED";
    ChatEvent::eventNames[FRIEND_UNREGISTERED] = "FRIEND_UNREGISTERED";
    ChatEvent::eventNames[FRIEND_NEW_CHAT_RECEIVED] = "FRIEND_NEW_CHAT_RECEIVED";
    ChatEvent::eventNames[FRIEND_CHAT_EDITED] = "FRIEND_CHAT_EDITED";
    ChatEvent::eventNames[FRIEND_CHAT_DELETED] = "FRIEND_CHAT_DELETED";
    ChatEvent::eventNames[FRIEND_CHAT_DELETE_STATUS_RECEIVED] = "FRIEND_CHAT_DELETE_STATUS_RECEIVED";
    ChatEvent::eventNames[FRIEND_CHAT_DELIVERED] = "FRIEND_CHAT_DELIVERED";
    ChatEvent::eventNames[FRIEND_CHAT_IS_SEEN] = "FRIEND_CHAT_IS_SEEN";
    ChatEvent::eventNames[FRIEND_CHAT_IS_SEEN_CONFIRMED] = "FRIEND_CHAT_IS_SEEN_CONFIRMED";
    ChatEvent::eventNames[FRIEND_CHAT_SENT] = "FRIEND_CHAT_SENT";
    ChatEvent::eventNames[FRIEND_CHAT_TYPING] = "FRIEND_CHAT_TYPING";
    ChatEvent::eventNames[FRIEND_CHAT_IDLE] = "FRIEND_CHAT_IDLE";
    ChatEvent::eventNames[FRIEND_CHAT_FAILED_TO_SEND] = "FRIEND_CHAT_FAILED_TO_SEND";
    ChatEvent::eventNames[FRIEND_BLOCKED] = "FRIEND_BLOCKED";
    ChatEvent::eventNames[FRIEND_UNBLOCKED] = "FRIEND_UNBLOCKED";
    ChatEvent::eventNames[FRIEND_BLOCK_UNBLOCK_CONFIRMED] = "FRIEND_BLOCK_UNBLOCK_CONFIRMED";
    
    ChatEvent::eventNames[FRIEND_FILE_TRANSFER_SESSION_REQUEST_SUCCESS] = "FRIEND_FILE_TRANSFER_SESSION_REQUEST_SUCCESS";
    ChatEvent::eventNames[FRIEND_FILE_TRANSFER_STREAM_REQUEST_SUCCESS] = "FRIEND_FILE_TRANSFER_STREAM_REQUEST_SUCCESS";
    ChatEvent::eventNames[FRIEND_FILE_TRANSFER_STREAM_REQUEST_RECEIVED] = "FRIEND_FILE_TRANSFER_STREAM_REQUEST_RECEIVED";
    ChatEvent::eventNames[FRIEND_FILE_TRANSFER_STREAM_REQUEST_FAILED] = "FRIEND_FILE_TRANSFER_STREAM_REQUEST_FAILED";
    ChatEvent::eventNames[FRIEND_FILE_TRANSFER_SESSION_REQUEST_FAILED] = "FRIEND_FILE_TRANSFER_SESSION_REQUEST_FAILED";
    ChatEvent::eventNames[GROUP_FILE_TRANSFER_SESSION_REQUEST_SUCCESS] = "GROUP_FILE_TRANSFER_SESSION_REQUEST_SUCCESS";
    ChatEvent::eventNames[GROUP_FILE_TRANSFER_STREAM_REQUEST_SUCCESS] = "GROUP_FILE_TRANSFER_STREAM_REQUEST_SUCCESS";
    ChatEvent::eventNames[GROUP_FILE_TRANSFER_STREAM_REQUEST_RECEIVED] = "GROUP_FILE_TRANSFER_STREAM_REQUEST_RECEIVED";
    ChatEvent::eventNames[GROUP_FILE_TRANSFER_STREAM_REQUEST_FAILED] = "GROUP_FILE_TRANSFER_STREAM_REQUEST_FAILED";
    ChatEvent::eventNames[GROUP_FILE_TRANSFER_SESSION_REQUEST_FAILED] = "GROUP_FILE_TRANSFER_SESSION_REQUEST_FAILED";
    
    ChatEvent::eventNames[OFFLINE_FRIEND_HISTORY_MESSAGE_RECEIVED] = "OFFLINE_FRIEND_HISTORY_MESSAGE_RECEIVED";
    ChatEvent::eventNames[OFFLINE_FRIEND_HISTORY_MESSAGE_CONFIRMATION_RECEIVED] = "OFFLINE_FRIEND_HISTORY_MESSAGE_CONFIRMATION_RECEIVED";
    ChatEvent::eventNames[OFFLINE_FRIEND_MESSAGES_STATUS_RECEIVED] = "OFFLINE_FRIEND_MESSAGES_STATUS_RECEIVED";
    ChatEvent::eventNames[OFFLINE_FRIEND_HISTORY_MESSAGE_RECEIVE_COMPLETED] = "OFFLINE_FRIEND_HISTORY_MESSAGE_RECEIVE_COMPLETED";
    ChatEvent::eventNames[OFFLINE_GROUP_HISTORY_MESSAGE_RECEIVED] = "OFFLINE_GROUP_HISTORY_MESSAGE_RECEIVED";
    ChatEvent::eventNames[OFFLINE_GROUP_HISTORY_MESSAGE_CONFIRMATION_RECEIVED] = "OFFLINE_GROUP_HISTORY_MESSAGE_CONFIRMATION_RECEIVED";
    ChatEvent::eventNames[OFFLINE_GROUP_HISTORY_MESSAGE_RECEIVE_COMPLETED] = "OFFLINE_GROUP_HISTORY_MESSAGE_RECEIVE_COMPLETED";
    ChatEvent::eventNames[OFFLINE_GROUP_INFORMATION_WITH_MEMBERS_RECEIVED] = "OFFLINE_GROUP_INFORMATION_WITH_MEMBERS_RECEIVED";
    ChatEvent::eventNames[OFFLINE_GROUP_INFORMATION_WITH_MEMBERS_REQUEST_STATUS] = "OFFLINE_GROUP_INFORMATION_WITH_MEMBERS_REQUEST_STATUS";
    ChatEvent::eventNames[OFFLINE_GROUP_INFORMATION_ACTIVITY_RECEIVED] = "OFFLINE_GROUP_INFORMATION_ACTIVITY_RECEIVED";
    ChatEvent::eventNames[OFFLINE_GROUP_INFORMATION_ACTIVITY_FROM_GROUP_HISTORY_MESSAGE_RECEIVED] = "OFFLINE_GROUP_INFORMATION_ACTIVITY_FROM_GROUP_HISTORY_MESSAGE_RECEIVED";
    ChatEvent::eventNames[OFFLINE_MY_GROUP_LIST_RECEIVED] = "OFFLINE_MY_GROUP_LIST_RECEIVED"; 
    ChatEvent::eventNames[OFFLINE_MY_GROUP_LIST_PAGING_RECEIVED] = "OFFLINE_MY_GROUP_LIST_PAGING_RECEIVED";
    ChatEvent::eventNames[OFFLINE_MY_GROUP_LIST_RECEIVED_COMPLETED] = "OFFLINE_MY_GROUP_LIST_RECEIVED_COMPLETED"; 
    ChatEvent::eventNames[GROUP_CREATED] = "GROUP_CREATED";
    ChatEvent::eventNames[GROUP_REGISTER_SUCCESS] = "GROUP_REGISTER_SUCCESS";
    ChatEvent::eventNames[GROUP_REGISTER_FAILURE] = "GROUP_REGISTER_FAILURE";
    ChatEvent::eventNames[GROUP_REGISTRATION_EXPIRED] = "GROUP_REGISTRATION_EXPIRED";
    ChatEvent::eventNames[GROUP_NEW_CHAT_RECEIVED] = "GROUP_NEW_CHAT_RECEIVED";
    ChatEvent::eventNames[GROUP_CHAT_DELIVERED] = "GROUP_CHAT_DELIVERED";
    ChatEvent::eventNames[GROUP_CHAT_DELETED] = "GROUP_CHAT_DELETED";
    ChatEvent::eventNames[GROUP_CHAT_DELETE_CONFIRMED] = "GROUP_CHAT_DELETE_CONFIRMED";
    ChatEvent::eventNames[GROUP_CHAT_SEEN] = "GROUP_CHAT_SEEN";
    ChatEvent::eventNames[GROUP_CHAT_SEEN_CONFIRMATION] = "GROUP_CHAT_SEEN_CONFIRMATION";
    ChatEvent::eventNames[GROUP_CHAT_SENT] = "GROUP_CHAT_SENT";
    ChatEvent::eventNames[GROUP_CHAT_TYPING] = "GROUP_CHAT_TYPING";
    ChatEvent::eventNames[GROUP_CHAT_IDLE] = "GROUP_CHAT_IDLE";
    ChatEvent::eventNames[GROUP_CHAT_EDITED] = "GROUP_CHAT_EDITED";
    ChatEvent::eventNames[GROUP_MEMBER_REMOVE_LEAVE_SENT] = "GROUP_MEMBER_REMOVE_LEAVE_SENT";
    ChatEvent::eventNames[GROUP_MEMBER_REMOVED_OR_LEFT] = "GROUP_MEMBER_REMOVED_OR_LEFT";
    ChatEvent::eventNames[GROUP_MEMBER_ADDED] = "GROUP_MEMBER_ADDED";
    ChatEvent::eventNames[GROUP_MEMBER_ADD_SENT] = "GROUP_MEMBER_ADD_SENT";
    ChatEvent::eventNames[GROUP_INFORMATION_RECEIVED] = "GROUP_INFORMATION_RECEIVED";
    ChatEvent::eventNames[GROUP_INFORMATION_SENT] = "GROUP_INFORMATION_SENT";
    ChatEvent::eventNames[GROUP_MEMBER_STATUS_CHANGED] = "GROUP_MEMBER_STATUS_CHANGED";
    ChatEvent::eventNames[GROUP_MEMBER_STATUS_CHANGE_SENT] = "GROUP_MEMBER_STATUS_CHANGE_SENT";
    ChatEvent::eventNames[GROUP_CHAT_FAILED_TO_SEND] = "GROUP_CHAT_FAILED_TO_SEND";
    ChatEvent::eventNames[SHOULD_CHECK_FRIEND_PRESENCE] = "SHOULD_CHECK_FRIEND_PRESENCE";
    ChatEvent::eventNames[SHOULD_UPDATE_SERVER_ADDRESS_FOR_FRIEND] = "SHOULD_UPDATE_SERVER_ADDRESS_FOR_FRIEND";
    ChatEvent::eventNames[SHOULD_REMOVE_DUPLICATE_INFO_FOR_FRIEND] = "SHOULD_REMOVE_DUPLICATE_INFO_FOR_FRIEND";
    ChatEvent::eventNames[SHOULD_UPDATE_SERVER_ADDRESS_FOR_GROUP] = "SHOULD_UPDATE_SERVER_ADDRESS_FOR_GROUP";
    ChatEvent::eventNames[SHOULD_CHECK_OFFLINE_SERVER_ADDRESS] = "SHOULD_CHECK_OFFLINE_SERVER_ADDRESS";
    ChatEvent::eventNames[SERVICE_IDLE_TIMEOUT] = "SERVICE_IDLE_TIMEOUT";
    ChatEvent::eventNames[SERVER_TIME_DIFFERENCE_SYNCED] = "SERVER_TIME_DIFFERENCE_SYNCED";
    ChatEvent::eventNames[CONVERSATION_LIST_REQUEST_STATUS] = "CONVERSATION_LIST_REQUEST_STATUS";
    ChatEvent::eventNames[CONVERSATION_LIST_RECEIVE_COMPLETED] = "CONVERSATION_LIST_RECEIVE_COMPLETED";
    ChatEvent::eventNames[FRIEND_CONVERSATION_LIST_RECEIVED] = "FRIEND_CONVERSATION_LIST_RECEIVED";
    ChatEvent::eventNames[GROUP_CONVERSATION_LIST_RECEIVED] = "GROUP_CONVERSATION_LIST_RECEIVED";
    ChatEvent::eventNames[CONVERSATION_LIST_DELETE_REQUEST_STATUS] = "CONVERSATION_LIST_DELETE_REQUEST_STATUS";
    ChatEvent::eventNames[MARK_CONVERSATION_LIST_SEEN_REQUEST_STATUS] = "MARK_CONVERSATION_LIST_SEEN_REQUEST_STATUS";
    
    ChatEvent::eventNames[PUBLIC_ROOM_CHAT_REGISTER_SUCCESS] = "PUBLIC_ROOM_CHAT_REGISTER_SUCCESS";
    ChatEvent::eventNames[PUBLIC_ROOM_CHAT_REGISTER_FAILURE] = "PUBLIC_ROOM_CHAT_REGISTER_FAILURE";
    ChatEvent::eventNames[PUBLIC_ROOM_CHAT_REGISTRATION_EXPIRED] = "PUBLIC_ROOM_CHAT_REGISTRATION_EXPIRED";
    ChatEvent::eventNames[PUBLIC_ROOM_CHAT_DELIVERED] = "PUBLIC_ROOM_CHAT_DELIVERED";
    ChatEvent::eventNames[PUBLIC_ROOM_CHAT_FAILED_TO_SEND] = "PUBLIC_ROOM_CHAT_FAILED_TO_SEND";
    ChatEvent::eventNames[PUBLIC_ROOM_CHAT_MESSAGE_RECEIVED] = "PUBLIC_ROOM_CHAT_MESSAGE_RECEIVED";
    ChatEvent::eventNames[PUBLIC_ROOM_LIST_RECEIVED] = "PUBLIC_ROOM_LIST_RECEIVED";
    ChatEvent::eventNames[PUBLIC_ROOM_LIST_REQUEST_STATUS] = "PUBLIC_ROOM_LIST_REQUEST_STATUS";
    ChatEvent::eventNames[PUBLIC_ROOM_INFORMATION_REQUEST_FAILED] = "PUBLIC_ROOM_INFORMATION_REQUEST_FAILED";
    ChatEvent::eventNames[PUBLIC_ROOM_CHAT_HISTORY_REQUEST_STATUS] = "PUBLIC_ROOM_CHAT_HISTORY_REQUEST_STATUS";
    ChatEvent::eventNames[PUBLIC_ROOM_CHAT_HISTORY_MESSAGE_RECEIVE_COMPLETED] = "PUBLIC_ROOM_CHAT_HISTORY_MESSAGE_RECEIVE_COMPLETED";
    ChatEvent::eventNames[PUBLIC_ROOM_MEMBER_LIST_REQUEST_STATUS] = "PUBLIC_ROOM_MEMBER_LIST_REQUEST_STATUS";
    ChatEvent::eventNames[PUBLIC_ROOM_CHAT_EDITED] = "PUBLIC_ROOM_CHAT_EDITED";
    ChatEvent::eventNames[PUBLIC_ROOM_CHAT_TYPING] = "PUBLIC_ROOM_CHAT_TYPING";
    ChatEvent::eventNames[PUBLIC_CHAT_MEMBER_LIST_RECEIVED] = "PUBLIC_CHAT_MEMBER_LIST_RECEIVED";
    ChatEvent::eventNames[PUBLIC_CHAT_MEMBER_COUNT_CHANGED] = "PUBLIC_CHAT_MEMBER_COUNT_CHANGED";
    ChatEvent::eventNames[PUBLIC_CHAT_MESSAGE_DELETED] = "PUBLIC_CHAT_MESSAGE_DELETED";
    ChatEvent::eventNames[PUBLIC_CHAT_MESSAGE_LIKED] = "PUBLIC_CHAT_MESSAGE_LIKED";
    ChatEvent::eventNames[PUBLIC_CHAT_MESSAGE_UNLIKED] = "PUBLIC_CHAT_MESSAGE_UNLIKED";
    ChatEvent::eventNames[PUBLIC_CHAT_MESSAGE_REPORTED] = "PUBLIC_CHAT_MESSAGE_REPORTED";
    ChatEvent::eventNames[SHOULD_CHECK_SERVER_ADDRESS_FOR_ROOM] = "SHOULD_CHECK_SERVER_ADDRESS_FOR_ROOM";
    ChatEvent::eventNames[ROOM_INFORMATION_RECEIVED] = "ROOM_INFORMATION_RECEIVED";
    ChatEvent::eventNames[ROOM_HISTORY_RECEIVED] = "ROOM_HISTORY_RECEIVED";
    ChatEvent::eventNames[SHADOW_IDS_INFO_REQUEST_FAILED] = "SHADOW_IDS_INFO_REQUEST_FAILED";
    ChatEvent::eventNames[SHADOW_IDS_INFO_RESPONSE_RECEIVED] = "SHADOW_IDS_INFO_RESPONSE_RECEIVED";
    ChatEvent::eventNames[FRIEND_GET_CHAT_MESSAGE_RECEIVED] = "FRIEND_GET_CHAT_MESSAGE_RECEIVED";
    ChatEvent::eventNames[GROUP_GET_CHAT_MESSAGE_RECEIVED] = "GROUP_GET_CHAT_MESSAGE_RECEIVED";
    ChatEvent::eventNames[FRIEND_GET_CHAT_MESSAGE_FAILED_TO_SEND] = "FRIEND_GET_CHAT_MESSAGE_FAILED_TO_SEND";
    ChatEvent::eventNames[GROUP_GET_CHAT_MESSAGE_FAILED_TO_SEND] = "GROUP_GET_CHAT_MESSAGE_FAILED_TO_SEND";
    ChatEvent::eventNames[PUBLIC_CHAT_ROOM_CATEGORY_LIST_RECEIVED] = "PUBLIC_CHAT_ROOM_CATEGORY_LIST_RECEIVED";
    ChatEvent::eventNames[PUBLIC_CHAT_LIKE_MEMBER_LIST_RECEIVED] = "PUBLIC_CHAT_LIKE_MEMBER_LIST_RECEIVED";
    ChatEvent::eventNames[PUBLIC_CHAT_DELETE_MESSAGE_REQUEST_STATUS] = "PUBLIC_CHAT_DELETE_MESSAGE_REQUEST_STATUS";
    ChatEvent::eventNames[PUBLIC_CHAT_LIKE_UNLIKE_REQUEST_STATUS] = "PUBLIC_CHAT_LIKE_UNLIKE_REQUEST_STATUS";
    ChatEvent::eventNames[PUBLIC_CHAT_REPORT_A_MESSAGE_REQUEST_STATUS] = "PUBLIC_CHAT_REPORT_A_MESSAGE_REQUEST_STATUS";
    ChatEvent::eventNames[PUBLIC_CHAT_LIKE_MEMBER_LIST_REQUEST_STATUS] = "PUBLIC_CHAT_LIKE_MEMBER_LIST_REQUEST_STATUS";
    ChatEvent::eventNames[OFFLINE_PUBLIC_CHAT_CATEGORY_LIST_REQUEST_STATUS] = "OFFLINE_PUBLIC_CHAT_CATEGORY_LIST_REQUEST_STATUS";
    ChatEvent::eventNames[DATA_COUNTED] = "DATA_COUNTED";
    ChatEvent::eventNames[GROUP_CHAT_MESSAGE_SEEN_LIST_RECEIVED] = "GROUP_CHAT_MESSAGE_SEEN_LIST_RECEIVED";
    ChatEvent::eventNames[GROUP_CHAT_MESSAGE_SEEN_LIST_CONFIRMATION_RECEIVED] = "GROUP_CHAT_MESSAGE_SEEN_LIST_CONFIRMATION_RECEIVED";
    ChatEvent::eventNames[SDK_ERROR] = "SDK_ERROR";
    ChatEvent::eventNames[INTERNAL_DETACH_HANDLER] = "INTERNAL_DETACH_HANDLER";
    ChatEvent::eventNames[LIVE_STREAM_CHAT_REGISTRATION_EXPIRED] = "LIVE_STREAM_CHAT_REGISTRATION_EXPIRED";
    ChatEvent::eventNames[LIVE_STREAM_CHAT_REGISTER_SUCCESS] = "LIVE_STREAM_CHAT_REGISTER_SUCCESS";
    ChatEvent::eventNames[LIVE_STREAM_CHAT_REGISTER_FAILURE] = "LIVE_STREAM_CHAT_REGISTER_FAILURE";
    ChatEvent::eventNames[SHOULD_UPDATE_SERVER_ADDRESS_FOR_LIVE_STREAM_CHAT] = "SHOULD_UPDATE_SERVER_ADDRESS_FOR_LIVE_STREAM_CHAT";
    ChatEvent::eventNames[LIVE_STREAM_CHAT_TYPING] = "LIVE_STREAM_CHAT_TYPING";
    ChatEvent::eventNames[LIVE_STREAM_CHAT_MESSAGE_RECEIVED] = "LIVE_STREAM_CHAT_MESSAGE_RECEIVED";
    ChatEvent::eventNames[LIVE_STREAM_CHAT_DELIVERED] = "LIVE_STREAM_CHAT_DELIVERED";
    ChatEvent::eventNames[LIVE_STREAM_CHAT_MESSAGE_FAILED] = "LIVE_STREAM_CHAT_MESSAGE_FAILED";
    ChatEvent::eventNames[SHOULD_UPDATE_PASSWORD] = "SHOULD_UPDATE_PASSWORD";
    
    ChatEvent::eventNames[SYNC_CONVERSATION_CONFIRMATION_RECEIVED] = "SYNC_CONVERSATION_CONFIRMATION_RECEIVED";
    ChatEvent::eventNames[SYNC_CONVERSATION_LIST_RECEIVED] = "SYNC_CONVERSATION_LIST_RECEIVED";
    ChatEvent::eventNames[SYNC_FRIEND_HISTORY_MESSAGE_CONFIRMATION_RECEIVED] = "SYNC_FRIEND_HISTORY_MESSAGE_CONFIRMATION_RECEIVED";
    ChatEvent::eventNames[SYNC_FRIEND_HISTORY_MESSAGE_RECEIVED] = "SYNC_FRIEND_HISTORY_MESSAGE_RECEIVED";
    ChatEvent::eventNames[SYNC_FRIEND_HISTORY_MESSAGE_RECEIVE_COMPLETED] = "SYNC_FRIEND_HISTORY_MESSAGE_RECEIVE_COMPLETED";
    ChatEvent::eventNames[SYNC_GROUP_HISTORY_MESSAGE_CONFIRMATION_RECEIVED] = "SYNC_GROUP_HISTORY_MESSAGE_CONFIRMATION_RECEIVED";
    ChatEvent::eventNames[SYNC_GROUP_HISTORY_MESSAGE_RECEIVED] = "SYNC_GROUP_HISTORY_MESSAGE_RECEIVED";
    ChatEvent::eventNames[SYNC_GROUP_HISTORY_MESSAGE_RECEIVE_COMPLETED] = "SYNC_GROUP_HISTORY_MESSAGE_RECEIVE_COMPLETED";
	ChatEvent::eventNames[GENERAL_ENCRYPTED_PACKET_EVENT] = "GENERAL_ENCRYPTED_PACKET_EVENT";

}

}
