/* 
 * File:   ChatEvent.h
 * Author: dipal
 *
 * Created on August 16, 2015, 6:00 PM
 */

#ifndef CHATEVENT_H
#define	CHATEVENT_H

#include "Event.h"
#include "PacketDTO.h"
#include "Types.h"
#include <memory>

namespace imsdk {
class ChatEvent : Event {
public:
    enum EventType {
        EVENT_HANDLER_ATTACHED,
        EVENT_HANDLER_DETACHED,
        FRIEND_REGISTER_SUCCESS,
        FRIEND_REGISTER_FAILURE,
        FRIEND_REGISTRATION_EXPIRED,
        FRIEND_UNREGISTERED,
        FRIEND_NEW_CHAT_RECEIVED,
        FRIEND_CHAT_EDITED,
        FRIEND_CHAT_DELETED,
        FRIEND_CHAT_DELETE_STATUS_RECEIVED,
        FRIEND_CHAT_DELIVERED,
        FRIEND_CHAT_IS_SEEN,
        FRIEND_CHAT_IS_SEEN_CONFIRMED,
        FRIEND_CHAT_SENT,
        FRIEND_CHAT_TYPING,
        FRIEND_CHAT_IDLE,
        FRIEND_CHAT_FAILED_TO_SEND,
        FRIEND_BLOCKED,
        FRIEND_UNBLOCKED,
        FRIEND_BLOCK_UNBLOCK_CONFIRMED,
//        FRIEND_FILE_TRANSFER_REQUEST_RECEIVED,
        FRIEND_FILE_TRANSFER_SESSION_REQUEST_SUCCESS,
        FRIEND_FILE_TRANSFER_STREAM_REQUEST_SUCCESS,
        FRIEND_FILE_TRANSFER_STREAM_REQUEST_RECEIVED,
        FRIEND_FILE_TRANSFER_STREAM_REQUEST_FAILED,
        FRIEND_FILE_TRANSFER_SESSION_REQUEST_FAILED,
        
        GROUP_FILE_TRANSFER_SESSION_REQUEST_SUCCESS,
        GROUP_FILE_TRANSFER_STREAM_REQUEST_SUCCESS,
        GROUP_FILE_TRANSFER_STREAM_REQUEST_RECEIVED,
        GROUP_FILE_TRANSFER_STREAM_REQUEST_FAILED,
        GROUP_FILE_TRANSFER_SESSION_REQUEST_FAILED,
        
        OFFLINE_FRIEND_HISTORY_MESSAGE_RECEIVED,
        OFFLINE_FRIEND_HISTORY_MESSAGE_CONFIRMATION_RECEIVED,
        OFFLINE_FRIEND_MESSAGES_STATUS_RECEIVED,
        OFFLINE_FRIEND_HISTORY_MESSAGE_RECEIVE_COMPLETED,
        OFFLINE_GROUP_HISTORY_MESSAGE_RECEIVED,
        OFFLINE_GROUP_HISTORY_MESSAGE_CONFIRMATION_RECEIVED,
        OFFLINE_GROUP_HISTORY_MESSAGE_RECEIVE_COMPLETED,
        OFFLINE_GROUP_INFORMATION_WITH_MEMBERS_RECEIVED,
        OFFLINE_GROUP_INFORMATION_WITH_MEMBERS_REQUEST_STATUS,
        OFFLINE_GROUP_INFORMATION_ACTIVITY_RECEIVED,
        OFFLINE_GROUP_INFORMATION_ACTIVITY_FROM_GROUP_HISTORY_MESSAGE_RECEIVED,
        OFFLINE_MY_GROUP_LIST_RECEIVED,
        OFFLINE_MY_GROUP_LIST_PAGING_RECEIVED,
        OFFLINE_MY_GROUP_LIST_RECEIVED_COMPLETED,
        GROUP_CREATED,
        GROUP_REGISTER_SUCCESS,
        GROUP_REGISTER_FAILURE,
        GROUP_REGISTRATION_EXPIRED,
        GROUP_NEW_CHAT_RECEIVED,
        GROUP_CHAT_DELIVERED,
        GROUP_CHAT_DELETED,
        GROUP_CHAT_DELETE_CONFIRMED,
        GROUP_CHAT_SEEN,
        GROUP_CHAT_SEEN_CONFIRMATION,
        GROUP_CHAT_SENT,
        GROUP_CHAT_TYPING,
        GROUP_CHAT_IDLE,
        GROUP_CHAT_EDITED,
        GROUP_MEMBER_REMOVE_LEAVE_SENT,
        GROUP_MEMBER_REMOVED_OR_LEFT,
        GROUP_MEMBER_ADDED,
        GROUP_MEMBER_ADD_SENT,
        GROUP_INFORMATION_RECEIVED,
        GROUP_INFORMATION_SENT,
        GROUP_MEMBER_STATUS_CHANGED,
        GROUP_MEMBER_STATUS_CHANGE_SENT,
        GROUP_CHAT_FAILED_TO_SEND,
        SHOULD_CHECK_FRIEND_PRESENCE,
        SHOULD_UPDATE_SERVER_ADDRESS_FOR_FRIEND,
        SHOULD_REMOVE_DUPLICATE_INFO_FOR_FRIEND,
        SHOULD_UPDATE_SERVER_ADDRESS_FOR_GROUP,
        SHOULD_CHECK_OFFLINE_SERVER_ADDRESS,
        SERVICE_IDLE_TIMEOUT,
        SERVER_TIME_DIFFERENCE_SYNCED,
        CONVERSATION_LIST_REQUEST_STATUS,
        CONVERSATION_LIST_RECEIVE_COMPLETED,
        FRIEND_CONVERSATION_LIST_RECEIVED,
        GROUP_CONVERSATION_LIST_RECEIVED,
        CONVERSATION_LIST_DELETE_REQUEST_STATUS,
        MARK_CONVERSATION_LIST_SEEN_REQUEST_STATUS,
        PUBLIC_ROOM_CHAT_REGISTER_SUCCESS,
        PUBLIC_ROOM_CHAT_REGISTER_FAILURE,
        PUBLIC_ROOM_CHAT_REGISTRATION_EXPIRED,
        PUBLIC_ROOM_CHAT_DELIVERED,
        PUBLIC_ROOM_CHAT_FAILED_TO_SEND,
        PUBLIC_ROOM_CHAT_MESSAGE_RECEIVED,
        PUBLIC_ROOM_LIST_RECEIVED,
        PUBLIC_ROOM_LIST_REQUEST_STATUS,
        PUBLIC_ROOM_INFORMATION_REQUEST_FAILED,
        PUBLIC_ROOM_CHAT_HISTORY_REQUEST_STATUS,
        PUBLIC_ROOM_CHAT_HISTORY_MESSAGE_RECEIVE_COMPLETED,
        PUBLIC_ROOM_MEMBER_LIST_REQUEST_STATUS,
        PUBLIC_ROOM_CHAT_EDITED,
        PUBLIC_ROOM_CHAT_TYPING,
        PUBLIC_CHAT_MEMBER_LIST_RECEIVED,
        PUBLIC_CHAT_MEMBER_COUNT_CHANGED,
        PUBLIC_CHAT_MESSAGE_DELETED,
        PUBLIC_CHAT_MESSAGE_LIKED,
        PUBLIC_CHAT_MESSAGE_UNLIKED,
        PUBLIC_CHAT_MESSAGE_REPORTED,
        SHOULD_CHECK_SERVER_ADDRESS_FOR_ROOM,
        ROOM_INFORMATION_RECEIVED,
        ROOM_HISTORY_RECEIVED,
        SHADOW_IDS_INFO_REQUEST_FAILED,
        SHADOW_IDS_INFO_RESPONSE_RECEIVED,
        FRIEND_GET_CHAT_MESSAGE_RECEIVED,
        GROUP_GET_CHAT_MESSAGE_RECEIVED,
        FRIEND_GET_CHAT_MESSAGE_FAILED_TO_SEND,
        GROUP_GET_CHAT_MESSAGE_FAILED_TO_SEND,
        PUBLIC_CHAT_ROOM_CATEGORY_LIST_RECEIVED,
        PUBLIC_CHAT_LIKE_MEMBER_LIST_RECEIVED,
        PUBLIC_CHAT_DELETE_MESSAGE_REQUEST_STATUS,
        PUBLIC_CHAT_LIKE_UNLIKE_REQUEST_STATUS,
        PUBLIC_CHAT_REPORT_A_MESSAGE_REQUEST_STATUS,
        PUBLIC_CHAT_LIKE_MEMBER_LIST_REQUEST_STATUS,
        OFFLINE_PUBLIC_CHAT_CATEGORY_LIST_REQUEST_STATUS,
        DATA_COUNTED,
        GROUP_CHAT_MESSAGE_SEEN_LIST_RECEIVED,
        GROUP_CHAT_MESSAGE_SEEN_LIST_CONFIRMATION_RECEIVED,
        INCOMING_CHAT_MEDIA_FILE,
        INCOMING_GROUP_CHAT_MEDIA_FILE,
        FILE_MANIFEST_UPLOADED,
        GROUP_FILE_MANIFEST_UPLOADED,
        CHAT_MEDIA_TRANSFER_PROGRESS,
        GROUP_CHAT_MEDIA_TRANSFER_PROGRESS,
        CHAT_MEDIA_DOWNLOAD_COMPLETED,
        GROUP_CHAT_MEDIA_DOWNLOAD_COMPLETED,
        CHAT_MEDIA_TRANSFER_FAILED,
        GROUP_CHAT_MEDIA_TRANSFER_FAILED,
        FRIEND_CHAT_MEDIA_TRANSFER_CANCELED,
        GROUP_CHAT_MEDIA_TRANSFER_CANCELED,
        CHAT_MEDIA_TRANSFER_DIRECTORY_ERROR,
        SHOULD_UPDATE_APP_SESSION_ID,
        SDK_ERROR,
        INTERNAL_DETACH_HANDLER,
        LIVE_STREAM_CHAT_REGISTRATION_EXPIRED,
        LIVE_STREAM_CHAT_REGISTER_SUCCESS,
        LIVE_STREAM_CHAT_REGISTER_FAILURE,
        SHOULD_UPDATE_SERVER_ADDRESS_FOR_LIVE_STREAM_CHAT,
        LIVE_STREAM_CHAT_TYPING,
        LIVE_STREAM_CHAT_MESSAGE_RECEIVED,
        LIVE_STREAM_CHAT_DELIVERED,
        LIVE_STREAM_CHAT_MESSAGE_FAILED,
        LIVE_STREAM_CHAT_BLOCK_USER_REQUEST_STATUS,
        LIVE_STREAM_CHAT_USER_BLOCKED,
		SHOULD_UPDATE_PASSWORD,
        ACTIVATE_DEACTIVATE_USER_ACCOUNT_STATUS,
        GET_USER_INFO_DETAILS_RECEIVED,
        GET_USER_INFO_DETAILS_FAILURE,
        SYNC_CONVERSATION_CONFIRMATION_RECEIVED,
        SYNC_CONVERSATION_LIST_RECEIVED,
        SYNC_FRIEND_HISTORY_MESSAGE_CONFIRMATION_RECEIVED,
        SYNC_FRIEND_HISTORY_MESSAGE_RECEIVED,
        SYNC_FRIEND_HISTORY_MESSAGE_RECEIVE_COMPLETED,
        SYNC_GROUP_HISTORY_MESSAGE_CONFIRMATION_RECEIVED,
        SYNC_GROUP_HISTORY_MESSAGE_RECEIVED,
        SYNC_GROUP_HISTORY_MESSAGE_RECEIVE_COMPLETED,
        ADD_NOTICE_STATUS,
		GENERAL_ENCRYPTED_PACKET_EVENT,
		GENERAL_ENCRYPTED_PACKET_CONFIRMATION_EVENT,
        NO_EVENT
    };

    ChatEvent();
    ChatEvent(EventType eventType, std::shared_ptr< PacketDTO> packet, ChatError errorCode = ChatError::NO_ERROR_IN_SDK);
    
    EventType getEventType();
    std::shared_ptr< PacketDTO> getPacket();
    ChatError getErrorCode();
    static std::string getEventName(EventType eventType);
    static void initEventNames();
    static std::vector<std::string> eventNames;
    
    virtual ~ChatEvent();
private:
    std::shared_ptr< PacketDTO> packet{nullptr};
    EventType eventType;
    ChatError errorCode;
    
};
}

#endif	/* CHATEVENT_H */

