/* 
 * File:   packet_template.cpp
 * Author: dipal
 * 
 * Created on July 22, 2015, 11:40 AM
 */

#include "PacketTemplate.h"

namespace imsdk {
PacketTemplate::PacketTemplate() {
    format = std::vector<std::vector<int> > (NUM_PACKET_TYPES);


    format[FRIEND_REGISTER]                               = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, PLATFORM, APP_VERSION, FRIEND_APP_TYPE, PAGE_OWNER_IDENTITY, OPTIONAL_FIELD, AUTH_SESSION_ID_LENGTH, AUTHSESSIONID };
    format[FRIEND_UNREGISTER]                             = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, ONLINE_STATUS, ONLINE_MOOD, OPTIONAL_FIELD, AUTH_SESSION_ID_LENGTH, AUTHSESSIONID };
    format[FRIEND_REGISTER_CONFIRMATION]                  = { PACKET_TYPE, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, CHAT_BINDING_PORT, SERVER_DATE };
    format[FRIEND_CHAT_IDEL]                              = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PLATFORM, OPTIONAL_FIELD, AUTH_SESSION_ID_LENGTH, AUTHSESSIONID };
    format[FRIEND_CHAT_MESSAGE_TYPING]                    = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PLATFORM, OPTIONAL_FIELD, PACKETID, AUTH_SESSION_ID_LENGTH, AUTHSESSIONID };
	format[FRIEND_CHAT_MESSAGE]						      = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, TIMEOUT, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, IS_SECRET_VISIBLE, OPTIONAL_FIELD, PLATFORM, APP_VERSION, FRIEND_APP_TYPE, PAGE_OWNER_IDENTITY };
    format[FRIEND_CALL_BUSY_MESSAGE]                      = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, TIMEOUT, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, IS_SECRET_VISIBLE};
	format[FRIEND_CHAT_MESSAGE_EDIT]					  = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, TIMEOUT, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, IS_SECRET_VISIBLE, OPTIONAL_FIELD, PLATFORM, APP_VERSION, FRIEND_APP_TYPE, PAGE_OWNER_IDENTITY };
	format[FRIEND_CHAT_MESSAGE_BROKEN]					  = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, TOTAL_NUMBER_OF_PACKETS, SEQUENCE_NUMBER, MESSAGE_TYPE, TIMEOUT, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, IS_SECRET_VISIBLE, OPTIONAL_FIELD, PLATFORM, APP_VERSION, FRIEND_APP_TYPE, PAGE_OWNER_IDENTITY };
	format[FRIEND_CHAT_MESSAGE_BROKEN_EDIT]				  = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, TOTAL_NUMBER_OF_PACKETS, SEQUENCE_NUMBER, MESSAGE_TYPE, TIMEOUT, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, IS_SECRET_VISIBLE, OPTIONAL_FIELD, PLATFORM, APP_VERSION, FRIEND_APP_TYPE, PAGE_OWNER_IDENTITY };
    format[FRIEND_CHAT_MULTIPLE_MESSAGE]                  = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_MESSAGES, FRIEND_CHAT_MULTIPLE_MESSAGE_INNER};
	format[GENERAL_ENCRYPTED_PACKET]					  = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, TYPE, INFORMATION_TYPE, INFORMATION_LENGTH , INFORMATION};
	format[GENERAL_ENCRYPTED_CONFIRMATION]					= { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, TYPE, INFORMATION_TYPE };
	format[USER_PASSWORD_UPDATE]                          = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID };
    format[USER_PASSWORD_UPDATE_CONFIRMATION]             = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID };
    format[FRIEND_CHAT_MESSAGE_DELIVERED]                 = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID };
    format[FRIEND_CHAT_MESSAGE_SENT]                      = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID };
    format[FRIEND_CHAT_MESSAGE_SEEN]                      = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_SEEN_PACKET};
    format[FRIEND_CHAT_MESSAGE_SEEN_CONFIRMATION]         = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID };
    format[FRIEND_CHAT_MULTIPLE_MESSAGE_DELETE]           = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_PACKETS, PLATFORM , MESSAGE_DELETE_TYPE };
    format[FRIEND_CHAT_MESSAGE_DELETE_CONFIRMATION]       = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID };
    format[FRIEND_BROKEN_PACKET]                          = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, TOTAL_NUMBER_OF_PACKETS, SEQUENCE_NUMBER, DATA_BYTES};
    format[FRIEND_BROKEN_PACKET_CONFIRMATION]             = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, SEQUENCE_NUMBER };
    format[FRIEND_BLOCK]                                  = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, BLOCK_UNBLOCK_DATE, IS_ADD_TO_BLOCK};
    format[FRIEND_UNBLOCK]                                = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, BLOCK_UNBLOCK_DATE};
    format[FRIEND_BLOCK_UNBLOCK_CONFIRMATION]             = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID };
    
    format[GROUP_REGISTER]                                = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, PLATFORM, APP_VERSION, OPTIONAL_FIELD, AUTH_SESSION_ID_LENGTH, AUTHSESSIONID };
    format[GROUP_UNREGISTER]                              = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, ONLINE_STATUS, ONLINE_MOOD, OPTIONAL_FIELD, AUTH_SESSION_ID_LENGTH, AUTHSESSIONID };
    format[GROUP_REGISTER_CONFIRMATION]                   = { PACKET_TYPE, GROUPID, PACKETID_LENGTH, PACKETID, CHAT_BINDING_PORT, SERVER_DATE };
    format[GROUP_INFORMATION]                             = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, ACTIVITY_TYPE};
    format[GROUP_INFORMATION_CONFIRMATION]                = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID };
    format[GROUP_MEMBER_ADD]                              = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, NUMBER_OF_MEMBERS_ID_N_S};
    format[GROUP_MEMBER_ADD_CONFIRMATION]                 = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID };
    format[GROUP_MEMBER_REMOVE_LEAVE]                     = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, NUMBER_OF_MEMBERS_ID, LEAVE_TYPE};
    format[GROUP_MEMBER_REMOVE_LEAVE_CONFIRMATION]        = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID };
    format[GROUP_MEMBER_TYPE_CHANGE]                      = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, NUMBER_OF_MEMBERS_ID_S};
    format[GROUP_MEMBER_TYPE_CHANGE_CONFIRMATION]         = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID };
    format[GROUP_CHAT_IDEL]                               = { PACKET_TYPE, USER_IDENTITY, GROUPID, PLATFORM, OPTIONAL_FIELD, AUTH_SESSION_ID_LENGTH, AUTHSESSIONID };
    format[GROUP_CHAT_MESSAGE_TYPING]                     = { PACKET_TYPE, USER_IDENTITY, GROUPID, PLATFORM, OPTIONAL_FIELD, PACKETID_LENGTH, PACKETID, AUTH_SESSION_ID_LENGTH, AUTHSESSIONID };
    format[GROUP_CHAT_MESSAGE]                            = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE};
    format[GROUP_CHAT_MESSAGE_EDIT]                       = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE};
    format[GROUP_CHAT_MESSAGE_BROKEN]                     = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, TOTAL_NUMBER_OF_PACKETS, SEQUENCE_NUMBER, MESSAGE_TYPE, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE};
    format[GROUP_CHAT_MESSAGE_BROKEN_EDIT]                = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, TOTAL_NUMBER_OF_PACKETS, SEQUENCE_NUMBER, MESSAGE_TYPE, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE};
    format[GROUP_CHAT_MULTIPLE_MESSAGE]                   = { };
    format[GROUP_CHAT_MESSAGE_DELIVERED]                  = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID };
    format[GROUP_CHAT_MESSAGE_SENT]                       = { PACKET_TYPE, GROUPID, PACKETID_LENGTH, PACKETID };
    format[GROUP_CHAT_MESSAGE_SEEN]                       = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, NUMBER_OF_PACKETS};
    format[GROUP_CHAT_MESSAGE_SEEN_CONFIRMATION]          = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID };
    format[GROUP_CHAT_MULTIPLE_MESSAGE_DELETE]            = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, NUMBER_OF_PACKETS};
    format[GROUP_CHAT_MESSAGE_DELETE_CONFIRMATION]        = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID };
    format[GROUP_CHAT_GET_MESSAGE_SEEN_LIST_REQUEST]      = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, ORIGINAL_PACKETID_LENGTH, ORIGINAL_PACKETID, PLATFORM };
    format[GROUP_CHAT_MESSAGE_SEEN_LIST]                  = { PACKET_TYPE, GROUPID, PACKETID_LENGTH, PACKETID, ORIGINAL_PACKETID_LENGTH, ORIGINAL_PACKETID, NUMBER_OF_MEMBERS_ID_T };
    format[GROUP_CHAT_MESSAGE_SEEN_LIST_CONFIRMATION]     = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID };
    format[GROUP_BROKEN_PACKET]                           = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, TOTAL_NUMBER_OF_PACKETS, SEQUENCE_NUMBER, DATA_BYTES };
    format[GROUP_BROKEN_PACKET_CONFIRMATION]              = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, SEQUENCE_NUMBER };
    
    format[OFFLINE_FRIEND_INFORMATION]                    = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, FULL_NAME_LENGTH, FULL_NAME, FRIEND_PLATFORM, FRIEND_ONLINE_STATUS, FRIEND_APP_TYPE, FRIEND_DEVICE_TOKEN_LENGTH, FRIEND_DEVICE_TOKEN, ONLINE_MOOD, IOS_VOIP_PUSH, PLATFORM, PROFILE_TYPE, FRIEND_PROFILE_TYPE };
    format[OFFLINE_FRIEND_INFORMATION_CONFIRMATION]       = { PACKET_TYPE, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID };
    format[OFFLINE_GET_REQUEST]                           = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, GROUP_UPDATE_DATE, BLOCK_UNBLOCK_DATE, APP_VERSION, PLATFORM, FRIEND_APP_TYPE, NUMBER_OF_PAGE};
    format[OFFLINE_GET_REQUEST_CONFIRMATION]              = { PACKET_TYPE, PACKETID_LENGTH, PACKETID, SERVER_DATE };
	format[OFFLINE_FRIEND_UNREAD_MESSAGE]				  = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_MESSAGES, OFFLINE_FRIEND_UNREAD_MESSAGE_INNER };
    format[OFFLINE_FRIEND_UNREAD_MESSAGE_CONFIRMATION]    = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_PACKETS};
	format[OFFLINE_FRIEND_HISTORY_MESSAGE_REQUEST]		  = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, UP_DOWN, LIMIT, PLATFORM, FRIEND_APP_TYPE, APP_VERSION, PAGE_OWNER_IDENTITY };
    format[OFFLINE_FRIEND_HISTORY_MESSAGE]                = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_MESSAGES, OFFLINE_FRIEND_HISTORY_MESSAGE_INNER, UP_DOWN};
    format[OFFLINE_FRIEND_HISTORY_MESSAGE_CONFIRMATION]   = { PACKET_TYPE, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID };
    format[OFFLINE_GET_FRIEND_MESSGAE_STATUS]             = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_PACKETS};
    format[OFFLINE_GET_FRIEND_MESSGAE_STATUS_CONFIRMATION]= { PACKET_TYPE, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_PACKETS_D_S};
    format[OFFLINE_GET_CONVERSATION_REQUEST]              = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, START_INDEX, LIMIT, CONVERSATION_TYPE, FRIEND_GROUP_ID, PLATFORM, APP_VERSION};
    format[OFFLINE_MESSAGE_CONVERSATION_LIST]             = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_MESSAGES_2B, OFFLINE_MESSAGE_CONVERSATION_LIST_INNER};
    format[OFFLINE_GROUP_IP_PORT]                         = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, PLATFORM, SERVER_IP_LENGTH, SERVER_IP, SERVER_REGISTER_PORT};
    format[OFFLINE_MY_GROUP_LIST]                         = { PACKET_TYPE, PACKETID_LENGTH, PACKETID, NUMBER_OF_GROUPS, PIVOTID_LENGTH, PIVOTID, UP_DOWN };
    format[OFFLINE_GROUP_UNREAD_MESSAGE]                  = { PACKET_TYPE, PACKETID_LENGTH, PACKETID, NUMBER_OF_MESSAGES,OFFLINE_GROUP_UNREAD_MESSAGE_INNER};
    format[OFFLINE_GROUP_UNREAD_MESSAGE_CONFIRMATION]     = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_PACKETS};
    format[OFFLINE_CREATE_GROUP]                          = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, GROUP_NAME_LENGTH, GROUP_NAME, GROUP_URL_LENGTH, GROUP_URL, NUMBER_OF_MEMBERS_ID_N_S};
    format[OFFLINE_CREATE_GROUP_CONFIRMATION]             = { PACKET_TYPE, GROUPID, PACKETID_LENGTH, PACKETID};
    format[OFFLINE_GROUP_HISTORY_MESSAGE_REQUEST]         = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, UP_DOWN, LIMIT, APP_VERSION };
    format[OFFLINE_GROUP_HISTORY_MESSAGE]                 = { PACKET_TYPE, GROUPID, PACKETID_LENGTH, PACKETID, NUMBER_OF_MESSAGES, OFFLINE_GROUP_HISTORY_MESSAGE_INNER, UP_DOWN};
    format[OFFLINE_GET_INFORMATION_WITH_MEMBERS]          = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID};
    format[OFFLINE_INFORMATION_WITH_MEMBERS]              = { PACKET_TYPE, GROUPID, PACKETID_LENGTH, PACKETID, GROUP_NAME_LENGTH, GROUP_NAME, GROUP_URL_LENGTH, GROUP_URL, NUMBER_OF_MEMBERS_DTO};
    format[DELETE_CONVERSATION_REQUEST]                   = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_CONVERSATION, PLATFORM };
    format[MARK_CONVERSATION_SEEN_REQUEST]                = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_CONVERSATION, PLATFORM };
    format[OFFLINE_GROUP_CONFIRMATION]                    = { PACKET_TYPE, GROUPID, PACKETID_LENGTH, PACKETID };
	format[OFFLINE_BROKEN_HISTORY_PACKET]				  = { PACKET_TYPE, PACKETID_LENGTH, PACKETID, TOTAL_NUMBER_OF_PACKETS, SEQUENCE_NUMBER, DATA_BYTES };
	format[OFFLINE_BROKEN_PACKET]						  = { PACKET_TYPE, PACKETID_LENGTH, PACKETID, TOTAL_NUMBER_OF_PACKETS, SEQUENCE_NUMBER, DATA_BYTES };
    format[OFFLINE_BROKEN_PACKET_CONFIRMATION]            = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, SEQUENCE_NUMBER };

    format[OFFLINE_MESSAGE_CONVERSATION_LIST_INNER]       = { PACKET_TYPE, USER_IDENTITY, FRIEND_GROUP_ID, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, UNREAD_COUNT, TIMEOUT};
    format[FRIEND_CHAT_MULTIPLE_MESSAGE_INNER]            = { PACKET_TYPE, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, TIMEOUT, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, IS_SECRET_VISIBLE};
	format[OFFLINE_FRIEND_UNREAD_MESSAGE_INNER]			  = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, TIMEOUT, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, IS_SECRET_VISIBLE };
    format[OFFLINE_FRIEND_HISTORY_MESSAGE_INNER]          = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, TIMEOUT, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, IS_SECRET_VISIBLE, MESSAGE_STATUS };
    format[OFFLINE_GROUP_UNREAD_MESSAGE_INNER]            = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE};
    format[OFFLINE_GROUP_HISTORY_MESSAGE_INNER]           = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE};
    
    format[OFFLINE_GROUP_UNREAD_MESSAGE_HEADER]           = { PACKET_TYPE, PACKETID_LENGTH, PACKETID};
    format[FRIEND_CHAT_MESSAGE_HEADER]                    = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID};
	format[OFFLINE_CREATE_GROUP_HEADER]					  = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID };
    format[ACTIVATE_DEACTIVATE_USER_ACCOUNT]              = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, ACCOUNT_ACTIVATION_STATUS, PLATFORM };
    format[ACTIVATE_DEACTIVATE_USER_ACCOUNT_CONFIRMATION] = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, ACCOUNT_ACTIVATION_STATUS };
    format[GET_USER_INFO]                                 = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, PLATFORM };
    format[USER_INFO_DETAILS]                             = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, FULL_NAME_LENGTH, FULL_NAME, FRIEND_PROFILE_IAMGE_URL_LENGTH, FRIEND_PROFILE_IAMGE_URL, PROFILE_TYPE, RING_ID };

    format[PUBLIC_ROOM_REGISTER]                          = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, ROOM_FULL_NAME_LENGTH, ROOM_FULL_NAME, MEMBER_PROFILE_URL_LENGTH, MEMBER_PROFILE_URL, PLATFORM, RING_ID };
    format[PUBLIC_ROOM_UNREGISTER]                        = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, RECEPIENT_IDENTITY, RING_ID };
    format[PUBLIC_ROOM_REGISTER_CONFIRMATION]             = { PACKET_TYPE, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, CHAT_BINDING_PORT, RECEPIENT_IDENTITY };
    format[PUBLIC_ROOM_CHAT_IDEL]                         = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PLATFORM };
    format[PUBLIC_ROOM_CHAT_MESSAGE_TYPING]               = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PLATFORM , ROOM_FULL_NAME_LENGTH, ROOM_FULL_NAME };
    format[PUBLIC_ROOM_CHAT_MESSAGE]                      = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, ROOM_FULL_NAME_LENGTH, ROOM_FULL_NAME, MEMBER_PROFILE_URL_LENGTH, MEMBER_PROFILE_URL };
    format[PUBLIC_ROOM_CHAT_MESSAGE_EDIT]                 = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, ROOM_FULL_NAME_LENGTH, ROOM_FULL_NAME, MEMBER_PROFILE_URL_LENGTH, MEMBER_PROFILE_URL };
    format[PUBLIC_ROOM_CHAT_MESSAGE_BROKEN]               = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, TOTAL_NUMBER_OF_PACKETS, SEQUENCE_NUMBER, MESSAGE_TYPE, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, ROOM_FULL_NAME_LENGTH, ROOM_FULL_NAME, MEMBER_PROFILE_URL_LENGTH, MEMBER_PROFILE_URL };
    format[PUBLIC_ROOM_CHAT_MESSAGE_BROKEN_EDIT]          = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, TOTAL_NUMBER_OF_PACKETS, SEQUENCE_NUMBER, MESSAGE_TYPE, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, ROOM_FULL_NAME_LENGTH, ROOM_FULL_NAME, MEMBER_PROFILE_URL_LENGTH, MEMBER_PROFILE_URL };
    format[PUBLIC_ROOM_CHAT_MESSAGE_DELIVERED]            = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID };
    format[PUBLIC_ROOM_CHAT_MESSAGE_SENT]                 = { PACKET_TYPE, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID };
    format[PUBLIC_CHAT_GET_MEMBER_LIST]                   = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, PAGING_STATE_LENGTH, PAGING_STATE, LIMIT, APP_VERSION };
    format[PUBLIC_CHAT_GET_MEMBER_LIST_CONFIRMATION]      = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID };
    format[PUBLIC_CHAT_MEMBER_LIST]                       = { PACKET_TYPE, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, PAGING_STATE_LENGTH, PAGING_STATE, NUMBER_OF_PUBLIC_CHAT_MEMBERS };
    format[PUBLIC_CHAT_MEMBER_COUNT_CHANGE]               = { PACKET_TYPE, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_PUBLIC_CHAT_MEMBERS_C };
    format[PUBLIC_CHAT_MEMBER_COUNT_CHANGE_CONFIRMATION]  = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID };
    
    format[OFFLINE_PUBLIC_ROOM_LIST_REQUEST]              = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, START_INDEX, LIMIT, PLATFORM };
    format[OFFLINE_PUBLIC_ROOM_LIST_SEARCH_REQUEST]       = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, START_INDEX, LIMIT, SEARCH_NAMELENGTH, SEARCHNAME, PUBLIC_CHAT_COUNTRY_LENGTH, PUBLIC_CHAT_COUNTRY, PUBLIC_CHAT_CATEGORY_LENGTH, PUBLIC_CHAT_CATEGORY, PLATFORM };
    format[OFFLINE_PUBLIC_ROOM_LIST_REQUEST_CONFIRMATION] = { PACKET_TYPE, PACKETID_LENGTH, PACKETID };
    format[OFFLINE_PUBLIC_ROOM_LIST]                      = { PACKET_TYPE, PACKETID_LENGTH, PACKETID, NUMBER_OF_ROOM };
    format[OFFLINE_PUBLIC_GET_ROOM_IPPORT]                = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, PLATFORM };
    format[OFFLINE_PUBLIC_ROOM_IPPORT_CONFIRMATION]       = { PACKET_TYPE, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, SERVER_IP_LENGTH, SERVER_IP, SERVER_REGISTER_PORT, NUMBER_OF_PUBLIC_CHAT_MEMBERS_C };
    format[OFFLINE_ROOM_INFORMATION_REQUEST]              = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, PLATFORM };
    format[OFFLINE_ROOM_INFORMATION]                      = { PACKET_TYPE, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, ROOM_FULL_NAME_LENGTH, ROOM_FULL_NAME, MEMBER_PROFILE_URL_LENGTH, MEMBER_PROFILE_URL };
    format[OFFLINE_ROOM_GET_HISTORY]                      = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, MONTH, YEAR, UP_DOWN, LIMIT, PLATFORM, APP_VERSION};
    format[OFFLINE_ROOM_GET_HISTORY_CONFIRMATION]         = { PACKET_TYPE, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID};
    format[OFFLINE_ROOM_HISTORY_MESSAGE_LIST]             = { PACKET_TYPE, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_MESSAGES, ROOM_HISTORY_INNER};
    
    
    format[ROOM_HISTORY_INNER]                            = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, ROOM_FULL_NAME_LENGTH, ROOM_FULL_NAME, MEMBER_PROFILE_URL_LENGTH, MEMBER_PROFILE_URL, PUBLIC_CHAT_LIKE_COUNT, PUBLIC_CHAT_ILIKE, PUBLIC_CHAT_IREPORT };
    format[OFFLINE_PUBLIC_ROOM_LIST_WITH_HISTORY_REQUEST] = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, START_INDEX, LIMIT, PLATFORM };
    format[OFFLINE_PUBLIC_ROOM_LIST_WITH_HISTORY]         = { PACKET_TYPE, PACKETID_LENGTH, PACKETID, NUMBER_OF_ROOM_WITH_HISTORY };
    
    format[ROOM_BROKEN_PACKET]                            = { PACKET_TYPE, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, TOTAL_NUMBER_OF_PACKETS, SEQUENCE_NUMBER, DATA_BYTES };
    format[ROOM_BROKEN_PACKET_CONFIRMATION]               = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, SEQUENCE_NUMBER };
    
    format[SHADOW_IDS_INFO_REQUEST]                       = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_SHADOW_ID, PLATFORM };
    format[SHADOW_IDS_INFO_RESPONSE]                      = { PACKET_TYPE, PACKETID_LENGTH, PACKETID, NUMBER_OF_SHADOW_INFO_ID };
    
    //Group file transfer
    format[GROUP_FILE_STREAM_REQUEST]                     = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, FILE_ID, FILE_ACCEPT_REJECT, FILE_OFFSET };
    format[GROUP_FILE_STREAM_REQUEST_CONFIRMATION]        = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, FILE_ID, FILE_ACCEPT_REJECT };
    format[GROUP_FILE_SESSION_REQUEST]                    = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, FILE_ID };
    format[GROUP_FILE_SESSION_REQUEST_CONFIRMATION]       = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, FILE_ID, FILE_TRANSFER_PORT };
    format[GROUP_FILE_IDEL]                               = { PACKET_TYPE, USER_IDENTITY, GROUPID, PLATFORM };
    
    //Anonymous chat support
    format[ANONYMOUS_REGISTER]                            = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, PLATFORM};
    format[ANONYMOUS_REGISTER_CONFIRMATION]               = { PACKET_TYPE, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, CHAT_BINDING_PORT, SERVER_DATE };
    format[ANONYMOUS_UNREGISTER]                          = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, ONLINE_STATUS, ONLINE_MOOD};
    format[FRIEND_CHAT_MESSAGE_ANONYMOUS]                 = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, TIMEOUT, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, IS_SECRET_VISIBLE, PLATFORM, ORIGINAL_USER_IDENTITY};
    format[FRIEND_CHAT_MESSAGE_EDIT_ANONYMOUS]            = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, TIMEOUT, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, IS_SECRET_VISIBLE, PLATFORM, ORIGINAL_USER_IDENTITY};
    format[FRIEND_CHAT_MESSAGE_BROKEN_ANONYMOUS]          = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, TOTAL_NUMBER_OF_PACKETS, SEQUENCE_NUMBER, MESSAGE_TYPE, TIMEOUT, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, IS_SECRET_VISIBLE, PLATFORM, ORIGINAL_USER_IDENTITY};
    format[FRIEND_CHAT_MESSAGE_BROKEN_EDIT_ANONYMOUS]     = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, TOTAL_NUMBER_OF_PACKETS, SEQUENCE_NUMBER, MESSAGE_TYPE, TIMEOUT, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, IS_SECRET_VISIBLE, PLATFORM, ORIGINAL_USER_IDENTITY};

    format[FRIEND_FILE_STREAM_REQUEST]                    = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, FILE_ID, FILE_ACCEPT_REJECT, FILE_OFFSET };
    format[FRIEND_FILE_STREAM_REQUEST_CONFIRMATION]       = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, FILE_ID, FILE_ACCEPT_REJECT };
    format[FRIEND_FILE_SESSION_REQUEST]                   = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, FILE_ID };
    format[FRIEND_FILE_SESSION_REQUEST_CONFIRMATION]      = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, FILE_ID, FILE_TRANSFER_PORT };
    format[FRIEND_FILE_IDEL]                              = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PLATFORM };
    
    format[FRIEND_GET_CHAT_MESSAGE]                       = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, PLATFORM };
    format[FRIEND_GET_CHAT_MESSAGE_CONFIRMATION]          = { PACKET_TYPE, ORIGINAL_PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, TIMEOUT, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, IS_SECRET_VISIBLE};
    format[GROUP_GET_CHAT_MESSAGE]                        = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, PLATFORM };
    format[GROUP_GET_CHAT_MESSAGE_CONFIRMATION]           = { PACKET_TYPE, ORIGINAL_PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE};
    
    format[PUBLIC_CHAT_DELETE_MESSAGE]                    = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_PACKETS };
    format[PUBLIC_CHAT_DELETE_MESSAGE_CONFIRMATION]       = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID };
    format[PUBLIC_CHAT_LIKE_A_MESSAGE]                    = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, RECEPIENT_IDENTITY, ORIGINAL_PACKETID_LENGTH, ORIGINAL_PACKETID };
    format[PUBLIC_CHAT_UNLIKE_A_MESSAGE]                  = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, RECEPIENT_IDENTITY, ORIGINAL_PACKETID_LENGTH, ORIGINAL_PACKETID };
    format[PUBLIC_CHAT_LIKE_UNLIKE_CONFIRMATION]          = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID };
    format[PUBLIC_CHAT_REPORT_A_MESSAGE]                  = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, RECEPIENT_IDENTITY, ORIGINAL_PACKETID_LENGTH, ORIGINAL_PACKETID, MESSAGE_LENGTH, MESSAGE };
    format[PUBLIC_CHAT_REPORT_A_MESSAGE_CONFIRMATION]     = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID };
    
    format[PUBLIC_CHAT_LIKE_MEMBER_LIST_REQUEST]          = { PACKET_TYPE, USER_IDENTITY, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, ORIGINAL_PACKETID_LENGTH, ORIGINAL_PACKETID, PUBLIC_CHAT_LAST_LIKER_ID, LIMIT, APP_VERSION };
    format[PUBLIC_CHAT_LIKE_MEMBER_LIST]                  = { PACKET_TYPE, ROOM_IDENTITY_LENGTH, ROOM_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_PUBLIC_CHAT_LIKERS_ID };
    format[OFFLINE_PUBLIC_CHAT_CATEGORY_LIST_REQUEST]     = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, PAGING_STATE_LENGTH, PAGING_STATE, LIMIT, PLATFORM};
    format[OFFLINE_PUBLIC_CHAT_CATEGORY_LIST]             = { PACKET_TYPE, PACKETID_LENGTH, PACKETID, NUMBER_OF_PUBLIC_ROOM_CATEGORY };
    
    //Live-Stream-Chat packet formats
    format[LIVE_STREAM_CHAT_REGISTER]                     = { PACKET_TYPE, USER_IDENTITY, PUBLISHER_ID, PACKETID_LENGTH, PACKETID, PLATFORM };
    format[LIVE_STREAM_CHAT_UNREGISTER]                   = { PACKET_TYPE, USER_IDENTITY, PUBLISHER_ID, PACKETID_LENGTH, PACKETID, ONLINE_STATUS, ONLINE_MOOD };
    format[LIVE_STREAM_CHAT_REGISTER_CONFIRMATION]        = { PACKET_TYPE, PUBLISHER_ID, PACKETID_LENGTH, PACKETID, CHAT_BINDING_PORT, SERVER_DATE };
    format[LIVE_STREAM_CHAT_IDEL]                         = { PACKET_TYPE, USER_IDENTITY, PUBLISHER_ID, PLATFORM };
    format[LIVE_STREAM_CHAT_MESSAGE_TYPING]               = { PACKET_TYPE, USER_IDENTITY, PUBLISHER_ID, PLATFORM };
    format[LIVE_STREAM_CHAT_MESSAGE]                      = { PACKET_TYPE, USER_IDENTITY, PUBLISHER_ID, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, MESSAGE_LENGTH, MESSAGE, MESSAGE_DATE, FULL_NAME_LENGTH, FULL_NAME };
    format[LIVE_STREAM_CHAT_MESSAGE_DELIVERED]            = { PACKET_TYPE, USER_IDENTITY, PUBLISHER_ID, PACKETID_LENGTH, PACKETID };
    format[LIVE_STREAM_CHAT_MESSAGE_SENT]                 = { PACKET_TYPE, PUBLISHER_ID, PACKETID_LENGTH, PACKETID };
    format[LIVE_STREAM_CHAT_BLOCK_USER]                   = { PACKET_TYPE, PUBLISHER_ID, USER_IDENTITY, PACKETID_LENGTH, PACKETID };
    format[LIVE_STREAM_CHAT_BLOCK_USER_CONFIRMATION]      = { PACKET_TYPE, PUBLISHER_ID, USER_IDENTITY, PACKETID_LENGTH, PACKETID };
    
    //Chunk media transfer
    format[FRIEND_INIT_CHUNK_FILE_DOWNLOAD]               = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, FILE_DOWNLOAD_ID_LENGTH, FILE_DOWNLOAD_ID, FILE_DOMAIN_TYPE, FILE_CHUNK_COUNT, FILE_CHUNK_SIZE, FILE_SIZE, MESSAGE_TYPE, TIMEOUT, MESSAGE_DATE, IS_SECRET_VISIBLE, FILE_CAPTION_LENGTH, FILE_CAPTION, FILE_WIDTH_OR_SIZE, FILE_HEIGHT_OR_DURATION};
    format[FRIEND_FILE_CHUNK_UPLOADED]                    = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, IS_FILE_MANIFEST, FILE_DOWNLOAD_ID_LENGTH, FILE_DOWNLOAD_ID, FILE_CHUNK_DOWNLOAD_KEY_LENGTH, FILE_CHUNK_DOWNLOAD_KEY};
    format[FRIEND_FILE_CHUNK_CONFIRMATION]                = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID };
    format[FRIEND_CHAT_MEDIA_TRANSFER_CANCEL]             = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID };
    
    format[GROUP_INIT_CHUNK_FILE_DOWNLOAD]                = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, FILE_DOWNLOAD_ID_LENGTH, FILE_DOWNLOAD_ID, FILE_DOMAIN_TYPE, FILE_CHUNK_COUNT, FILE_CHUNK_SIZE, FILE_SIZE, MESSAGE_TYPE, MESSAGE_DATE, FILE_CAPTION_LENGTH, FILE_CAPTION, FILE_WIDTH_OR_SIZE, FILE_HEIGHT_OR_DURATION};
    format[GROUP_FILE_CHUNK_UPLOADED]                     = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, IS_FILE_MANIFEST, FILE_DOWNLOAD_ID_LENGTH, FILE_DOWNLOAD_ID, FILE_CHUNK_DOWNLOAD_KEY_LENGTH, FILE_CHUNK_DOWNLOAD_KEY};
    format[GROUP_FILE_CHUNK_CONFIRMATION]                 = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID };
    format[GROUP_CHAT_MEDIA_TRANSFER_CANCEL]              = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID };

    format[GET_SYNC_CONVERSATION_REQUEST]                 = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, LAST_SYNC_TIME, PLATFORM };
    format[SYNC_CONVERSATION_CONFIRMATION]                = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, SERVER_DATE };
    format[SYNC_CONVERSATION_LIST]                        = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_MESSAGES_2B, OFFLINE_MESSAGE_CONVERSATION_LIST_INNER };

    format[SYNC_FRIEND_HISTORY_MESSAGE_REQUEST]           = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, LAST_SYNC_TIME, PLATFORM, FRIEND_APP_TYPE, APP_VERSION, PAGE_OWNER_IDENTITY, LIMIT, UP_DOWN };
    format[SYNC_FRIEND_HISTORY_MESSAGE_CONFIRMATION]      = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID };
    format[SYNC_FRIEND_HISTORY_MESSAGE]                   = { PACKET_TYPE, USER_IDENTITY, FRIEND_IDENTITY, PACKETID_LENGTH, PACKETID, NUMBER_OF_MESSAGES, OFFLINE_FRIEND_HISTORY_MESSAGE_INNER, MESSAGE_DATE, UP_DOWN };

    format[SYNC_GROUP_HISTORY_MESSAGE_REQUEST]            = { PACKET_TYPE, USER_IDENTITY, GROUPID, PACKETID_LENGTH, PACKETID, LAST_SYNC_TIME, APP_VERSION, PLATFORM, LIMIT, UP_DOWN };
    format[SYNC_GROUP_HISTORY_MESSAGE_CONFIRMATION]       = { PACKET_TYPE, GROUPID, PACKETID_LENGTH, PACKETID };
    format[SYNC_GROUP_HISTORY_MESSAGE]                    = { PACKET_TYPE, GROUPID, PACKETID_LENGTH, PACKETID, NUMBER_OF_MESSAGES, OFFLINE_GROUP_HISTORY_MESSAGE_INNER, MESSAGE_DATE, UP_DOWN };

    format[GET_MY_GROUP_LIST_PAGING]                      = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, PIVOTID_LENGTH, PIVOTID, LIMIT, UP_DOWN, PLATFORM };
    format[ADD_NOTICE]                                    = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID, MESSAGE_TYPE, DISBURSE_TIME, EXPIRE_TIME, NOTICE_LENGTH, NOTICE, ISO_COUNTRY_LENGTH, ISO_COUNTRY };
    format[ADD_NOTICE_CONFIRMATION]                       = { PACKET_TYPE, USER_IDENTITY, PACKETID_LENGTH, PACKETID };



}

std::vector<int> PacketTemplate::getFormat(size_t packetType)
{
    if (packetType >= format.size())
    {
        return {};
    }
    
    return format[packetType];
}

PacketTemplate::~PacketTemplate() {
}
}
