/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ringid_imsdk_InternetChecker */

#ifndef _Included_com_ringid_imsdk_InternetChecker
#define _Included_com_ringid_imsdk_InternetChecker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ringid_imsdk_InternetChecker
 * Method:    checkInternetConnection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ringid_imsdk_InternetChecker_checkInternetConnection
  (JNIEnv *, jobject);

/*
 * Class:     com_ringid_imsdk_InternetChecker
 * Method:    ctor
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_InternetChecker_ctor
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
