/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ringid_imsdk_Chat */

#ifndef _Included_com_ringid_imsdk_Chat
#define _Included_com_ringid_imsdk_Chat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    ctor
 * Signature: (JLjava/lang/String;Ljava/lang/String;ILjava/lang/String;IILjava/lang/String;IJLjava/util/ArrayList;Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;ILjava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_Chat_ctor
  (JNIEnv *, jobject, jlong, jstring, jstring, jint, jstring, jint, jint, jstring, jint, jlong, jobject, jstring, jstring, jboolean, jstring, jint, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    reinitialize
 * Signature: (JLjava/lang/String;Ljava/lang/String;ILjava/lang/String;IILjava/lang/String;IJLjava/util/ArrayList;ZLjava/lang/String;Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_Chat_reinitialize
  (JNIEnv *, jobject, jlong, jstring, jstring, jint, jstring, jint, jint, jstring, jint, jlong, jobject, jboolean, jstring, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    setOfflineServer
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_Chat_setOfflineServer
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    setAuthenticationServer
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_Chat_setAuthenticationServer
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    isExistsFriendConnection
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ringid_imsdk_Chat_isExistsFriendConnection
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    isExistsGroupConnection
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ringid_imsdk_Chat_isExistsGroupConnection
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    requestForOffline
 * Signature: (JJ)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_requestForOffline
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    updateFriendRegisterServer
 * Signature: (JJLjava/lang/String;I)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_updateFriendRegisterServer
  (JNIEnv *, jobject, jlong, jlong, jstring, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    updateFriendStatusAndMood
 * Signature: (JJII)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_updateFriendStatusAndMood
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    deleteFriendChatMessage
 * Signature: (JJLjava/util/ArrayList;I)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_deleteFriendChatMessage
  (JNIEnv *, jobject, jlong, jlong, jobject, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    requestFriendChatHistory
 * Signature: (JJLjava/lang/String;II)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_requestFriendChatHistory
  (JNIEnv *, jobject, jlong, jlong, jstring, jint, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getFriendMessageStatus
 * Signature: (JJLjava/util/ArrayList;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getFriendMessageStatus
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    blockFriend
 * Signature: (JLjava/lang/String;JJZ)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_blockFriend
  (JNIEnv *, jobject, jlong, jstring, jlong, jlong, jboolean);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    unblockFriend
 * Signature: (JLjava/lang/String;JJ)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_unblockFriend
  (JNIEnv *, jobject, jlong, jstring, jlong, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    deleteGroupChatMessage
 * Signature: (JLjava/util/ArrayList;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_deleteGroupChatMessage
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    registerFriendChat
 * Signature: (JLjava/lang/String;JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;IIIIJI)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_registerFriendChat
  (JNIEnv *, jobject, jlong, jstring, jlong, jstring, jstring, jstring, jint, jint, jstring, jint, jint, jint, jint, jlong, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    unregisterFriendChat
 * Signature: (JJII)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_unregisterFriendChat
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    sendFriendChat
 * Signature: (Ljava/lang/String;JJIILjava/lang/String;JZ)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_sendFriendChat
  (JNIEnv *, jobject, jstring, jlong, jlong, jint, jint, jstring, jlong, jboolean);

//sendGeneralEncryptedInformation

JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_sendGeneralEncryptedInformation
(JNIEnv *, jobject, jlong, jlong, jstring, jint, jint, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    dontSendPendingMessages
 * Signature: (JJ)Lcom/ringid/imsdk/ApiStatus;
 */


JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_dontSendPendingMessages
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    sendFriendCallBusyMessage
 * Signature: (JJLjava/lang/String;JLjava/lang/String;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_sendFriendCallBusyMessage
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    sendFriendCallLogMessage
 * Signature: (JJLjava/lang/String;JLjava/lang/String;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_sendFriendCallLogMessage
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    editFriendChat
 * Signature: (Ljava/lang/String;JJIILjava/lang/String;JZ)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_editFriendChat
  (JNIEnv *, jobject, jstring, jlong, jlong, jint, jint, jstring, jlong, jboolean);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    seenFriendChat
 * Signature: (JJLjava/util/ArrayList;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_seenFriendChat
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    typingFriendChat
 * Signature: (JJ)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_typingFriendChat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    registerEventHandler
 * Signature: (Lcom/ringid/imsdk/IChatEventHandler;)V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_Chat_registerEventHandler
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    editGroupChat
 * Signature: (Ljava/lang/String;JILjava/lang/String;J)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_editGroupChat
  (JNIEnv *, jobject, jstring, jlong, jint, jstring, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    registerGroupChat
 * Signature: (JLjava/lang/String;IJ)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_registerGroupChat
  (JNIEnv *, jobject, jlong, jstring, jint, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    unregisterGroupChat
 * Signature: (JII)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_unregisterGroupChat
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    sendGroupChat
 * Signature: (Ljava/lang/String;JILjava/lang/String;J)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_sendGroupChat
  (JNIEnv *, jobject, jstring, jlong, jint, jstring, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    seenGroupChat
 * Signature: (JLjava/util/ArrayList;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_seenGroupChat
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getGroupMessageSeenList
 * Signature: (JLjava/lang/String;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getGroupMessageSeenList
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getConversationList
 * Signature: (JIIIJ)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getConversationList
  (JNIEnv *, jobject, jlong, jint, jint, jint, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    deleteConversation
 * Signature: (JLjava/util/ArrayList;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_deleteConversation
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    markConversationSeen
 * Signature: (JLjava/util/ArrayList;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_markConversationSeen
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    updateUserPassword
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_Chat_updateUserPassword
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    typingGroupChat
 * Signature: (J)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_typingGroupChat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    removeGroupMembers
 * Signature: (JLjava/util/ArrayList;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_removeGroupMembers
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    changeGroupName
 * Signature: (JLjava/lang/String;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_changeGroupName
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    changeGroupUrl
 * Signature: (JLjava/lang/String;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_changeGroupUrl
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    addGroupMembers
 * Signature: (JLjava/util/ArrayList;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_addGroupMembers
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    changeGroupMemberStatus
 * Signature: (JLjava/util/ArrayList;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_changeGroupMemberStatus
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    createGroup
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/util/ArrayList;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_createGroup
  (JNIEnv *, jobject, jlong, jstring, jstring, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    requestGroupChatHistory
 * Signature: (JLjava/lang/String;II)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_requestGroupChatHistory
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getGroupInformationWithMembers
 * Signature: (J)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getGroupInformationWithMembers
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    leaveGroup
 * Signature: (JZ)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_leaveGroup
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    unregisterEventHandler
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_Chat_unregisterEventHandler
  (JNIEnv *, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    setLogfile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_Chat_setLogfile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getFriendInformation
 * Signature: (JJ)Lcom/ringid/imsdk/FriendInformation;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getFriendInformation
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getGroupInformation
 * Signature: (J)Lcom/ringid/imsdk/GroupInformation;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getGroupInformation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getRegisteredFriendsList
 * Signature: (J)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getRegisteredFriendsList
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getRegisteredGroupList
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getRegisteredGroupList
  (JNIEnv *, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    cleanUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_Chat_cleanUp
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getPendingFriendMessages
 * Signature: (J)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getPendingFriendMessages
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getPendingGroupMessages
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getPendingGroupMessages
  (JNIEnv *, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    registerPublicRoomChat
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;J)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_registerPublicRoomChat
  (JNIEnv *, jobject, jstring, jstring, jstring, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    sendPublicRoomChat
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;JLjava/lang/String;Ljava/lang/String;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_sendPublicRoomChat
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jlong, jstring, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    editPublicRoomChat
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;JLjava/lang/String;Ljava/lang/String;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_editPublicRoomChat
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jlong, jstring, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getRoomList
 * Signature: (II)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getRoomList
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getRoomListWithHistory
 * Signature: (II)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getRoomListWithHistory
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getRoomMemberList
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getRoomMemberList
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    searchRoomList
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_searchRoomList
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    unregisterPublicRoomChat
 * Signature: (Ljava/lang/String;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_unregisterPublicRoomChat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    typingPublicRoomChat
 * Signature: (Ljava/lang/String;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_typingPublicRoomChat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    isExistsRoomConnection
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ringid_imsdk_Chat_isExistsRoomConnection
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getRoomInformation
 * Signature: (Ljava/lang/String;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getRoomInformation
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    requestRoomChatHistory
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIII)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_requestRoomChatHistory
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getGroupFileTransferIdlePacket
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ringid_imsdk_Chat_getGroupFileTransferIdlePacket
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    generatePacketId
 * Signature: (J)Lcom/ringid/imsdk/PacketTimeId;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_generatePacketId__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    generatePacketId
 * Signature: (JJ)Lcom/ringid/imsdk/PacketTimeId;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_generatePacketId__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    generateGroupId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ringid_imsdk_Chat_generateGroupId
  (JNIEnv *, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ringid_imsdk_Chat_version
  (JNIEnv *, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getRingIdPackageName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ringid_imsdk_Chat_getRingIdPackageName
  (JNIEnv *, jclass);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getRingIncPackageName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ringid_imsdk_Chat_getRingIncPackageName
  (JNIEnv *, jclass);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getCurrentServerSyncedTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ringid_imsdk_Chat_getCurrentServerSyncedTime
  (JNIEnv *, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getTimeFromPacketId
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ringid_imsdk_Chat_getTimeFromPacketId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    registerAnonymousFriendChat
 * Signature: (JJJLjava/lang/String;IILjava/lang/String;III)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_registerAnonymousFriendChat
  (JNIEnv *, jobject, jlong, jlong, jlong, jstring, jint, jint, jstring, jint, jint, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    unregisterAnonymousFriendChat
 * Signature: (JJII)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_unregisterAnonymousFriendChat
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getShadowIdInfo
 * Signature: (Ljava/util/ArrayList;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getShadowIdInfo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    setLogEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_Chat_setLogEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    enterPublicChatScreen
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_Chat_enterPublicChatScreen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    exitPublicChatScreen
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_Chat_exitPublicChatScreen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getDataSentReceived
 * Signature: ()Lcom/ringid/imsdk/DataCounter;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getDataSentReceived
  (JNIEnv *, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    deletePublicChatMessage
 * Signature: (Ljava/lang/String;Ljava/util/ArrayList;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_deletePublicChatMessage
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    likePublicChatMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_likePublicChatMessage
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    unlikePublicChatMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_unlikePublicChatMessage
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    reportPublicChatMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;JLjava/lang/String;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_reportPublicChatMessage
  (JNIEnv *, jobject, jstring, jstring, jlong, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getPublicChatLikeMemberList
 * Signature: (Ljava/lang/String;Ljava/lang/String;JI)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getPublicChatLikeMemberList
  (JNIEnv *, jobject, jstring, jstring, jlong, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getPublicChatRoomCategoryList
 * Signature: (Ljava/lang/String;I)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getPublicChatRoomCategoryList
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    registerLiveStreamChat
 * Signature: (JLjava/lang/String;ILjava/lang/String;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_registerLiveStreamChat
  (JNIEnv *, jobject, jlong, jstring, jint, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    unregisterLiveStreamChat
 * Signature: (JII)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_unregisterLiveStreamChat
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    typingLiveStreamChat
 * Signature: (J)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_typingLiveStreamChat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    sendLiveStreamChat
 * Signature: (Ljava/lang/String;JILjava/lang/String;J)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_sendLiveStreamChat
  (JNIEnv *, jobject, jstring, jlong, jint, jstring, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    blockUserFromLiveStreamChat
 * Signature: (JLjava/lang/String;)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_blockUserFromLiveStreamChat
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    checkInternetConnection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ringid_imsdk_Chat_checkInternetConnection
  (JNIEnv *, jobject);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    sendFriendChatMedia
 * Signature: (JJLjava/lang/String;ILjava/lang/String;Ljava/lang/String;IIIJZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ringid_imsdk_Chat_sendFriendChatMedia
  (JNIEnv *, jobject, jlong, jlong, jstring, jint, jstring, jstring, jint, jint, jint, jlong, jboolean);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    downloadFriendChatMedia
 * Signature: (JJLjava/lang/String;Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ringid_imsdk_Chat_downloadFriendChatMedia
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring, jint, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    acceptChatMedia
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ringid_imsdk_Chat_acceptChatMedia
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    sendGroupChatMedia
 * Signature: (JLjava/lang/String;ILjava/lang/String;Ljava/lang/String;IIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ringid_imsdk_Chat_sendGroupChatMedia
  (JNIEnv *, jobject, jlong, jstring, jint, jstring, jstring, jint, jint, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    downloadGroupChatMedia
 * Signature: (JJLjava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ringid_imsdk_Chat_downloadGroupChatMedia
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getPendingChatMediaList
 * Signature: (IZZ)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getPendingChatMediaList
  (JNIEnv *, jobject, jint, jboolean, jboolean);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    cancelChatMediaTransfer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_Chat_cancelChatMediaTransfer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    updateAppSessionID
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_Chat_updateAppSessionID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    addUserPage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_Chat_addUserPage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    activateOrDeactivateUserAccount
 * Signature: (Z)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_activateOrDeactivateUserAccount
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    removeUserPage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ringid_imsdk_Chat_removeUserPage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getSyncedConversation
 * Signature: (JLjava/lang/String;J)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getSyncedConversation
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getSyncedFriendHistoryMessage
 * Signature: (JJLjava/lang/String;JII)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getSyncedFriendHistoryMessage
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong, jint, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getSyncedGroupHistoryMessage
 * Signature: (JJLjava/lang/String;JII)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getSyncedGroupHistoryMessage
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong, jint, jint);

/*
 * Class:     com_ringid_imsdk_Chat
 * Method:    getMyGroupListPaging
 * Signature: (JLjava/lang/String;Ljava/lang/String;II)Lcom/ringid/imsdk/ApiStatus;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_Chat_getMyGroupListPaging
  (JNIEnv *, jobject, jlong, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
