/*
 * File:   ChatParserTest.h
 * Author: dipal
 *
 * Created on Aug 4, 2015, 5:04:18 PM
 */

#ifndef CHATPARSERTEST_H
#define	CHATPARSERTEST_H

#include <cppunit/extensions/HelperMacros.h>

#include "../src/ChatParser.h"
#include "../src/PacketDTO.h"
#include "../src/PacketTemplate.h"

typedef long long ll;

class ChatParserTest : public CPPUNIT_NS::TestFixture {
    CPPUNIT_TEST_SUITE(ChatParserTest);

    CPPUNIT_TEST(CHAT_REGISTER_ToByte);
    CPPUNIT_TEST(CHAT_REGISTER_ToDTO);

    CPPUNIT_TEST(CHAT_FRIEND_UNREGISTERED_ToByte);
    CPPUNIT_TEST(CHAT_FRIEND_UNREGISTERED_ToDTO);

    CPPUNIT_TEST(CHAT_REGISTER_CONFIRMATION_ToByte);
    CPPUNIT_TEST(CHAT_REGISTER_CONFIRMATION_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_UNREGISTER_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_UNREGISTER_ToDTO);

    CPPUNIT_TEST(CHAT_FRIEND_ToByte);
    CPPUNIT_TEST(CHAT_FRIEND_ToDTO);

    CPPUNIT_TEST(CHAT_DELIVERED_ToByte);
    CPPUNIT_TEST(CHAT_DELIVERED_ToDTO);

    CPPUNIT_TEST(CHAT_SEEN_ToByte);
    CPPUNIT_TEST(CHAT_SEEN_ToDTO);

    CPPUNIT_TEST(CHAT_SENT_ToByte);
    CPPUNIT_TEST(CHAT_SENT_ToDTO);

    CPPUNIT_TEST(CHAT_TYPING_ToByte);
    CPPUNIT_TEST(CHAT_TYPING_ToDTO);

    CPPUNIT_TEST(CHAT_IDEL_ToByte);
    CPPUNIT_TEST(CHAT_IDEL_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_REGISTER_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_REGISTER_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_REG_CONFIRMATION_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_REG_CONFIRMATION_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_DELIVERED_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_DELIVERED_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_SEEN_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_SEEN_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_SENT_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_SENT_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_TYPING_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_TYPING_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_IDEL_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_IDEL_ToDTO);

    CPPUNIT_TEST(CHAT_FRIEND_OFFLINE_0_ToByte);
    CPPUNIT_TEST(CHAT_FRIEND_OFFLINE_0_ToDTO);

    CPPUNIT_TEST(CHAT_FRIEND_OFFLINE_1_ToByte);
    CPPUNIT_TEST(CHAT_FRIEND_OFFLINE_1_ToDTO);

    CPPUNIT_TEST(CHAT_FRIEND_OFFLINE_5_ToByte);
    CPPUNIT_TEST(CHAT_FRIEND_OFFLINE_5_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_OFFLINE_0_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_OFFLINE_0_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_OFFLINE_1_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_OFFLINE_1_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_OFFLINE_5_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_OFFLINE_5_ToDTO);

    CPPUNIT_TEST(CHAT_GET_OFFLINE_ToByte);
    CPPUNIT_TEST(CHAT_GET_OFFLINE_ToDTO);

    CPPUNIT_TEST(CHAT_OFFLINE_CONFIRMATION_ToByte);
    CPPUNIT_TEST(CHAT_OFFLINE_CONFIRMATION_ToDTO);


    CPPUNIT_TEST(FRIEND_CHAT_DELETE_ToByte);
    CPPUNIT_TEST(FRIEND_CHAT_DELETE_ToDTO);

    CPPUNIT_TEST(FRIEND_CHAT_DELETE_CONFIRMATION_ToByte);
    CPPUNIT_TEST(FRIEND_CHAT_DELETE_CONFIRMATION_ToDTO);

    CPPUNIT_TEST(GROUP_CHAT_DELETE_ToByte);
    CPPUNIT_TEST(GROUP_CHAT_DELETE_ToDTO);

    CPPUNIT_TEST(GROUP_CHAT_DELETE_CONFIRMATION_ToByte);
    CPPUNIT_TEST(GROUP_CHAT_DELETE_CONFIRMATION_ToDTO);

    CPPUNIT_TEST(FRIEND_INFORMATION_ToByte);
    CPPUNIT_TEST(FRIEND_INFORMATION_ToDTO);

    CPPUNIT_TEST(FRIEND_INFORMATION_CONFIRMATION_ToByte);
    CPPUNIT_TEST(FRIEND_INFORMATION_CONFIRMATION_ToDTO);

    CPPUNIT_TEST(FILE_TOTAL_SEQUENCE_ToByte);
    CPPUNIT_TEST(FILE_TOTAL_SEQUENCE_ToDTO);

    CPPUNIT_TEST(FILE_TOTAL_SEQUENCE_CONFIRMATION_ToByte);
    CPPUNIT_TEST(FILE_TOTAL_SEQUENCE_CONFIRMATION_ToDTO);

    CPPUNIT_TEST(FILE_STREAM_SEND_ToByte);
    CPPUNIT_TEST(FILE_STREAM_SEND_ToDTO);

    CPPUNIT_TEST(FILE_STREAM_SEND_CONFIRMATION_ToByte);
    CPPUNIT_TEST(FILE_STREAM_SEND_CONFIRMATION_ToDTO);

    CPPUNIT_TEST(GROUP_MEMBERS_ToByte);
    CPPUNIT_TEST(GROUP_MEMBERS_ToDTO);

    CPPUNIT_TEST(GROUP_MEMBERS_CONFIRMATION_ToByte);
    CPPUNIT_TEST(GROUP_MEMBERS_CONFIRMATION_ToDTO);

    CPPUNIT_TEST(GET_GROUP_MEMBERS_ToByte);
    CPPUNIT_TEST(GET_GROUP_MEMBERS_ToDTO);

    CPPUNIT_TEST(GROUP_MEMBER_REMOVE_LEAVE_ToByte);
    CPPUNIT_TEST(GROUP_MEMBER_REMOVE_LEAVE_ToDTO);

    CPPUNIT_TEST(GROUP_MEMBER_REMOVE_LEAVE_CONFIRMATION_ToByte);
    CPPUNIT_TEST(GROUP_MEMBER_REMOVE_LEAVE_CONFIRMATION_ToDTO);

    CPPUNIT_TEST(GROUP_DELETE_ToByte);
    CPPUNIT_TEST(GROUP_DELETE_ToDTO);

    CPPUNIT_TEST(GROUP_DELETE_CONFIRMATION_ToByte);
    CPPUNIT_TEST(GROUP_DELETE_CONFIRMATION_ToDTO);

    CPPUNIT_TEST(MULTIPLE_FRIEND_CHAT_DELETE_ToByte);
    CPPUNIT_TEST(MULTIPLE_FRIEND_CHAT_DELETE_ToDTO);

    CPPUNIT_TEST(MULTIPLE_GROUP_CHAT_DELETE_ToByte);
    CPPUNIT_TEST(MULTIPLE_GROUP_CHAT_DELETE_ToDTO);

    CPPUNIT_TEST(FRIEND_CHAT_EDIT_ToByte);
    CPPUNIT_TEST(FRIEND_CHAT_EDIT_ToDTO);

    CPPUNIT_TEST(GROUP_CHAT_EDIT_ToByte);
    CPPUNIT_TEST(GROUP_CHAT_EDIT_ToDTO);

    CPPUNIT_TEST(MULTIPLE_CHAT_FOR_FRIEND_ToByte);
    CPPUNIT_TEST(MULTIPLE_CHAT_FOR_FRIEND_ToDTO);

    CPPUNIT_TEST(BROCKEN_CHAT_FOR_FRIEND_ToByte);
    CPPUNIT_TEST(BROCKEN_CHAT_FOR_FRIEND_ToDTO);

    CPPUNIT_TEST(BROCKEN_CHAT_FOR_GROUP_ToByte);
    CPPUNIT_TEST(BROCKEN_CHAT_FOR_GROUP_ToDTO);

    CPPUNIT_TEST(EDIT_BROCKEN_CHAT_FOR_FRIEND_ToByte);
    CPPUNIT_TEST(EDIT_BROCKEN_CHAT_FOR_FRIEND_ToDTO);

    CPPUNIT_TEST(EDIT_BROCKEN_CHAT_FOR_GROUP_ToByte);
    CPPUNIT_TEST(EDIT_BROCKEN_CHAT_FOR_GROUP_ToDTO);


    CPPUNIT_TEST(CHAT_FRIEND_FILE_STREAM_REQUEST_ToByte);
    CPPUNIT_TEST(CHAT_FRIEND_FILE_STREAM_REQUEST_ToDTO);

    CPPUNIT_TEST(CHAT_FRIEND_FILE_STREAM_REQUEST_CONFIRMATION_ToByte);
    CPPUNIT_TEST(CHAT_FRIEND_FILE_STREAM_REQUEST_CONFIRMATION_ToDTO);

    CPPUNIT_TEST(CHAT_FRIEND_FILE_STREAM_SEND_ToByte);
    CPPUNIT_TEST(CHAT_FRIEND_FILE_STREAM_SEND_ToDTO);

    CPPUNIT_TEST(CHAT_FRIEND_FILE_STREAM_SEND_CONFIRMATION_ToByte);
    CPPUNIT_TEST(CHAT_FRIEND_FILE_STREAM_SEND_CONFIRMATION_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_FILE_STREAM_REQUEST_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_FILE_STREAM_REQUEST_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_FILE_STREAM_REQUEST_CONFIRMATION_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_FILE_STREAM_REQUEST_CONFIRMATION_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_FILE_STREAM_SEND_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_FILE_STREAM_SEND_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_FILE_STREAM_SEND_CONFIRMATION_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_FILE_STREAM_SEND_CONFIRMATION_ToDTO);

    CPPUNIT_TEST(CHAT_FRIEND_OFFLINE_CONFIRMATION_ToByte);
    CPPUNIT_TEST(CHAT_FRIEND_OFFLINE_CONFIRMATION_ToDTO);

    CPPUNIT_TEST(CHAT_GROUP_OFFLINE_CONFIRMATION_ToByte);
    CPPUNIT_TEST(CHAT_GROUP_OFFLINE_CONFIRMATION_ToDTO);
    
    CPPUNIT_TEST(CHAT_FRIEND_BLOCK_ToByte);
    CPPUNIT_TEST(CHAT_FRIEND_BLOCK_ToDTO);
    
    CPPUNIT_TEST(CHAT_FRIEND_UNBLOCK_ToByte);
    CPPUNIT_TEST(CHAT_FRIEND_UNBLOCK_ToDTO);
    
    CPPUNIT_TEST(CHAT_BLOCK_UNBLOCK_CONFIRMATION_ToByte);
    CPPUNIT_TEST(CHAT_BLOCK_UNBLOCK_CONFIRMATION_ToDTO);
    
    CPPUNIT_TEST(GROUP_MEMBER_ADD_ToByte);
    CPPUNIT_TEST(GROUP_MEMBER_ADD_ToDTO);
    
    CPPUNIT_TEST(GROUP_MEMBER_ADD_CONFIRMATION_ToByte);
    CPPUNIT_TEST(GROUP_MEMBER_ADD_CONFIRMATION_ToDTO);
    
    CPPUNIT_TEST(GROUP_INFORMATION_ToByte);
    CPPUNIT_TEST(GROUP_INFORMATION_ToDTO);
    
    CPPUNIT_TEST(GET_GROUP_INFORMATION_ToByte);
    CPPUNIT_TEST(GET_GROUP_INFORMATION_ToDTO);
    
    CPPUNIT_TEST(GROUP_INFORMATION_CONFIRMATION_ToByte);
    CPPUNIT_TEST(GROUP_INFORMATION_CONFIRMATION_ToDTO);
    
    CPPUNIT_TEST(GROUP_MEMBER_STATUS_CHANGE_ToByte);
    CPPUNIT_TEST(GROUP_MEMBER_STATUS_CHANGE_ToDTO);
    
    CPPUNIT_TEST(GROUP_MEMBER_STATUS_CHANGE_CONFIRMATION_ToByte);
    CPPUNIT_TEST(GROUP_MEMBER_STATUS_CHANGE_CONFIRMATION_ToDTO);


    CPPUNIT_TEST_SUITE_END();

public:
    ChatParserTest();
    virtual ~ChatParserTest();
    void setUp();
    void tearDown();

private:

    bool isEqualData(ByteArray data, ByteArray expectedData);

    void CHAT_REGISTER_ToByte();
    void CHAT_REGISTER_ToDTO();

    void CHAT_FRIEND_UNREGISTERED_ToByte();
    void CHAT_FRIEND_UNREGISTERED_ToDTO();

    void CHAT_REGISTER_CONFIRMATION_ToByte();
    void CHAT_REGISTER_CONFIRMATION_ToDTO();

    void CHAT_GROUP_UNREGISTER_ToByte();
    void CHAT_GROUP_UNREGISTER_ToDTO();

    void CHAT_FRIEND_ToByte();
    void CHAT_FRIEND_ToDTO();

    void CHAT_DELIVERED_ToByte();
    void CHAT_DELIVERED_ToDTO();

    void CHAT_SEEN_ToByte();
    void CHAT_SEEN_ToDTO();

    void CHAT_SENT_ToByte();
    void CHAT_SENT_ToDTO();

    void CHAT_TYPING_ToByte();
    void CHAT_TYPING_ToDTO();

    void CHAT_IDEL_ToByte();
    void CHAT_IDEL_ToDTO();

    void CHAT_GROUP_REGISTER_ToByte();
    void CHAT_GROUP_REGISTER_ToDTO();

    void CHAT_GROUP_REG_CONFIRMATION_ToByte();
    void CHAT_GROUP_REG_CONFIRMATION_ToDTO();

    void CHAT_GROUP_ToByte();
    void CHAT_GROUP_ToDTO();

    void CHAT_GROUP_DELIVERED_ToByte();
    void CHAT_GROUP_DELIVERED_ToDTO();

    void CHAT_GROUP_SEEN_ToByte();
    void CHAT_GROUP_SEEN_ToDTO();

    void CHAT_GROUP_SENT_ToByte();
    void CHAT_GROUP_SENT_ToDTO();

    void CHAT_GROUP_TYPING_ToByte();
    void CHAT_GROUP_TYPING_ToDTO();

    void CHAT_GROUP_IDEL_ToByte();
    void CHAT_GROUP_IDEL_ToDTO();

    void CHAT_FRIEND_OFFLINE_0_ToByte();
    void CHAT_FRIEND_OFFLINE_0_ToDTO();

    void CHAT_FRIEND_OFFLINE_1_ToByte();
    void CHAT_FRIEND_OFFLINE_1_ToDTO();

    void CHAT_FRIEND_OFFLINE_5_ToByte();
    void CHAT_FRIEND_OFFLINE_5_ToDTO();

    void CHAT_GROUP_OFFLINE_0_ToByte();
    void CHAT_GROUP_OFFLINE_0_ToDTO();

    void CHAT_GROUP_OFFLINE_1_ToByte();
    void CHAT_GROUP_OFFLINE_1_ToDTO();

    void CHAT_GROUP_OFFLINE_5_ToByte();
    void CHAT_GROUP_OFFLINE_5_ToDTO();

    void CHAT_GET_OFFLINE_ToByte();
    void CHAT_GET_OFFLINE_ToDTO();

    void CHAT_OFFLINE_CONFIRMATION_ToByte();
    void CHAT_OFFLINE_CONFIRMATION_ToDTO();


    void FRIEND_CHAT_DELETE_ToByte();
    void FRIEND_CHAT_DELETE_ToDTO();

    void FRIEND_CHAT_DELETE_CONFIRMATION_ToByte();
    void FRIEND_CHAT_DELETE_CONFIRMATION_ToDTO();

    void GROUP_CHAT_DELETE_ToByte();
    void GROUP_CHAT_DELETE_ToDTO();

    void GROUP_CHAT_DELETE_CONFIRMATION_ToByte();
    void GROUP_CHAT_DELETE_CONFIRMATION_ToDTO();

    void FRIEND_INFORMATION_ToByte();
    void FRIEND_INFORMATION_ToDTO();

    void FRIEND_INFORMATION_CONFIRMATION_ToByte();
    void FRIEND_INFORMATION_CONFIRMATION_ToDTO();

    void FILE_TOTAL_SEQUENCE_ToByte();
    void FILE_TOTAL_SEQUENCE_ToDTO();

    void FILE_TOTAL_SEQUENCE_CONFIRMATION_ToByte();
    void FILE_TOTAL_SEQUENCE_CONFIRMATION_ToDTO();

    void FILE_STREAM_SEND_ToByte();
    void FILE_STREAM_SEND_ToDTO();

    void FILE_STREAM_SEND_CONFIRMATION_ToByte();
    void FILE_STREAM_SEND_CONFIRMATION_ToDTO();

    void GROUP_MEMBERS_ToByte();
    void GROUP_MEMBERS_ToDTO();

    void GROUP_MEMBERS_CONFIRMATION_ToByte();
    void GROUP_MEMBERS_CONFIRMATION_ToDTO();

    void GET_GROUP_MEMBERS_ToByte();
    void GET_GROUP_MEMBERS_ToDTO();

    void GROUP_MEMBER_REMOVE_LEAVE_ToByte();
    void GROUP_MEMBER_REMOVE_LEAVE_ToDTO();

    void GROUP_MEMBER_REMOVE_LEAVE_CONFIRMATION_ToByte();
    void GROUP_MEMBER_REMOVE_LEAVE_CONFIRMATION_ToDTO();

    void GROUP_DELETE_ToByte();
    void GROUP_DELETE_ToDTO();

    void GROUP_DELETE_CONFIRMATION_ToByte();
    void GROUP_DELETE_CONFIRMATION_ToDTO();

    void MULTIPLE_FRIEND_CHAT_DELETE_ToByte();
    void MULTIPLE_FRIEND_CHAT_DELETE_ToDTO();

    void MULTIPLE_GROUP_CHAT_DELETE_ToByte();
    void MULTIPLE_GROUP_CHAT_DELETE_ToDTO();

    void FRIEND_CHAT_EDIT_ToByte();
    void FRIEND_CHAT_EDIT_ToDTO();

    void GROUP_CHAT_EDIT_ToByte();
    void GROUP_CHAT_EDIT_ToDTO();

    void MULTIPLE_CHAT_FOR_FRIEND_ToByte();
    void MULTIPLE_CHAT_FOR_FRIEND_ToDTO();

    void BROCKEN_CHAT_FOR_FRIEND_ToByte();
    void BROCKEN_CHAT_FOR_FRIEND_ToDTO();

    void BROCKEN_CHAT_FOR_GROUP_ToByte();
    void BROCKEN_CHAT_FOR_GROUP_ToDTO();

    void EDIT_BROCKEN_CHAT_FOR_FRIEND_ToByte();
    void EDIT_BROCKEN_CHAT_FOR_FRIEND_ToDTO();

    void EDIT_BROCKEN_CHAT_FOR_GROUP_ToByte();
    void EDIT_BROCKEN_CHAT_FOR_GROUP_ToDTO();


    void CHAT_FRIEND_FILE_STREAM_REQUEST_ToByte();
    void CHAT_FRIEND_FILE_STREAM_REQUEST_ToDTO();

    void CHAT_FRIEND_FILE_STREAM_REQUEST_CONFIRMATION_ToByte();
    void CHAT_FRIEND_FILE_STREAM_REQUEST_CONFIRMATION_ToDTO();

    void CHAT_FRIEND_FILE_STREAM_SEND_ToByte();
    void CHAT_FRIEND_FILE_STREAM_SEND_ToDTO();

    void CHAT_FRIEND_FILE_STREAM_SEND_CONFIRMATION_ToByte();
    void CHAT_FRIEND_FILE_STREAM_SEND_CONFIRMATION_ToDTO();

    void CHAT_GROUP_FILE_STREAM_REQUEST_ToByte();
    void CHAT_GROUP_FILE_STREAM_REQUEST_ToDTO();

    void CHAT_GROUP_FILE_STREAM_REQUEST_CONFIRMATION_ToByte();
    void CHAT_GROUP_FILE_STREAM_REQUEST_CONFIRMATION_ToDTO();

    void CHAT_GROUP_FILE_STREAM_SEND_ToByte();
    void CHAT_GROUP_FILE_STREAM_SEND_ToDTO();

    void CHAT_GROUP_FILE_STREAM_SEND_CONFIRMATION_ToByte();
    void CHAT_GROUP_FILE_STREAM_SEND_CONFIRMATION_ToDTO();

    void CHAT_FRIEND_OFFLINE_CONFIRMATION_ToByte();
    void CHAT_FRIEND_OFFLINE_CONFIRMATION_ToDTO();

    void CHAT_GROUP_OFFLINE_CONFIRMATION_ToByte();
    void CHAT_GROUP_OFFLINE_CONFIRMATION_ToDTO();

    void CHAT_FRIEND_BLOCK_ToByte();
    void CHAT_FRIEND_BLOCK_ToDTO();
    
    void CHAT_FRIEND_UNBLOCK_ToByte();
    void CHAT_FRIEND_UNBLOCK_ToDTO();
    
    void CHAT_BLOCK_UNBLOCK_CONFIRMATION_ToByte();
    void CHAT_BLOCK_UNBLOCK_CONFIRMATION_ToDTO();
    
    void GROUP_MEMBER_ADD_ToByte();
    void GROUP_MEMBER_ADD_ToDTO();
    
    void GROUP_MEMBER_ADD_CONFIRMATION_ToByte();
    void GROUP_MEMBER_ADD_CONFIRMATION_ToDTO();
    
    void GROUP_INFORMATION_ToByte();
    void GROUP_INFORMATION_ToDTO();
    
    void GET_GROUP_INFORMATION_ToByte();
    void GET_GROUP_INFORMATION_ToDTO();
    
    void GROUP_INFORMATION_CONFIRMATION_ToByte();
    void GROUP_INFORMATION_CONFIRMATION_ToDTO();
    
    void GROUP_MEMBER_STATUS_CHANGE_ToByte();
    void GROUP_MEMBER_STATUS_CHANGE_ToDTO();
    
    void GROUP_MEMBER_STATUS_CHANGE_CONFIRMATION_ToByte();
    void GROUP_MEMBER_STATUS_CHANGE_CONFIRMATION_ToDTO();
};

#endif	/* CHATPARSERTEST_H */

