/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ringid_imsdk_ChatParser */

#ifndef _Included_com_ringid_imsdk_ChatParser
#define _Included_com_ringid_imsdk_ChatParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ringid_imsdk_ChatParser
 * Method:    parse
 * Signature: ([B)Lcom/ringid/imsdk/MessageDTO;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_ChatParser_parse___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_ringid_imsdk_ChatParser
 * Method:    parseHeader
 * Signature: ([B)Lcom/ringid/imsdk/MessageDTO;
 */
JNIEXPORT jobject JNICALL Java_com_ringid_imsdk_ChatParser_parseHeader
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_ringid_imsdk_ChatParser
 * Method:    parse
 * Signature: (Lcom/ringid/imsdk/MessageDTO;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ringid_imsdk_ChatParser_parse__Lcom_ringid_imsdk_MessageDTO_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ringid_imsdk_ChatParser
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ringid_imsdk_ChatParser_version
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
